Day 3, Topic 3: Handling Missing Data – Filling

In [1]:
import pandas as pd

df = pd.read_csv('titanic.csv')

In [2]:
#Fill with a Constant Value
df['Age_filled_constant'] = df['Age'].fillna(30)

df[['Age', 'Age_filled_constant']].head(10)

    Age  Age_filled_constant
0  22.0                 22.0
1  38.0                 38.0
2  26.0                 26.0
3  35.0                 35.0
4  35.0                 35.0
5   NaN                 30.0
6  54.0                 54.0
7   2.0                  2.0
8  27.0                 27.0
9  14.0                 14.0

In [6]:
#Fill with Summary Statistics – Mean, Median, Mode
#with mean
age_mean = df['Age'].mean()
filled_age_mean = df['Age'].fillna(age_mean)

#Median (often better for skewed data):

age_median = df['Age'].median()
filled_age_median = df['Age'].fillna(age_median)

#Mode (for categorical columns):

mode_embarked = df['Embarked'].mode()[0]
df['Embarked_filled'] = df['Embarked'].fillna(mode_embarked)

In [10]:
#Forward Fill and Backward Fill (method)

df['Age'].ffill()
df['Age'].bfill()

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    26.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [11]:
#Fill Different Columns with Different Values

fill_values = {
    'Age': df['Age'].median(),
    'Embarked': df['Embarked'].mode()[0],
    'Cabin': 'Unknown'
}

df_filled = df.fillna(fill_values)

In [13]:
#The inplace Parameter
#df['Age'].fillna(df['Age'].median(), inplace=True)

In [14]:
#Practice Activity: Filling Missing Data

import pandas as pd

df = pd.read_csv('titanic.csv')

In [27]:
"""#Task 1: Fill missing Age values with the median age. 
# Verify that there are no missing Age values remaining."""
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Age'].isna().sum()

np.int64(0)

In [28]:
"""Task 2: Fill missing Embarked values with the mode (most frequent value). 
What is the mode? Verify no missing Embarked remain."""
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df['Embarked'].isna().sum()

np.int64(0)

In [24]:
"""Task 3: Create a new column Cabin_filled that fills missing Cabin values with the 
string 'Unknown'. Display the value counts of Cabin_filled.
"""
df['Cabin_filled'] = df['Cabin'].fillna('Unknown')
df['Cabin_filled'].value_counts()

Cabin_filled
Unknown        687
C23 C25 C27      4
G6               4
B96 B98          4
C22 C26          3
              ...
E34              1
C7               1
C54              1
E36              1
C148             1
Name: count, Length: 148, dtype: int64

In [25]:
"""Task 4: Use forward fill on the Age column (create a copy Age_ffill). 
Compare the first 10 rows of original Age, Age_ffill, and median-filled Age. 
What do you notice about forward fill?"""

df['Age_ffill'] = df['Age'].ffill()
df['Age_median'] = df['Age'].fillna(df['Age'].median())
df[['Age', 'Age_ffill', 'Age_median']].head(10)

    Age  Age_ffill  Age_median
0  22.0       22.0        22.0
1  38.0       38.0        38.0
2  26.0       26.0        26.0
3  35.0       35.0        35.0
4  35.0       35.0        35.0
5   NaN       35.0        28.0
6  54.0       54.0        54.0
7   2.0        2.0         2.0
8  27.0       27.0        27.0
9  14.0       14.0        14.0

In [29]:
"""Task 5 (Bonus): Fill all missing values in the entire DataFrame at once using a dictionary: 
Age with median, Embarked with mode, Cabin with 'Unknown'. 
Confirm the DataFrame has no missing values."""

fill_values = {
    'Age': df['Age'].median(),
    'Embarked': df['Embarked'].mode(),
    'Cabin': 'Unknown'
}

df_filled = df.fillna(fill_values)

df_filled.isna().sum().sum()

np.int64(0)

In [31]:
#Day 3, Topic 4: Handling Duplicates

import pandas as pd
data = {
    'Name': ['Faizan', 'Ali', 'Usman', 'Faizan', 'Ali'],
    'Age': [25, 30, 35, 25, 30],
    'City': ['NYC', 'LA', 'Chicago', 'NYC', 'LA']
}
df = pd.DataFrame(data)

df

     Name  Age     City
0  Faizan   25      NYC
1     Ali   30       LA
2   Usman   35  Chicago
3  Faizan   25      NYC
4     Ali   30       LA

In [32]:
#Identifying Duplicates with .duplicated()
df.duplicated()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [33]:
df.duplicated().sum()

np.int64(2)

In [34]:
#Dropping Duplicates with .drop_duplicates()
df_unique = df.drop_duplicates()
df_unique

     Name  Age     City
0  Faizan   25      NYC
1     Ali   30       LA
2   Usman   35  Chicago

In [38]:
df.drop_duplicates(keep=False)

    Name  Age     City
2  Usman   35  Chicago

In [40]:
#Considering Only Specific Columns (subset)
df.duplicated(subset=['Name', 'Age'])

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [41]:
# Drop duplicates based on subset
df.drop_duplicates(subset=['Name', 'Age'])

     Name  Age     City
0  Faizan   25      NYC
1     Ali   30       LA
2   Usman   35  Chicago

In [42]:
#Practice Activity: Handling Duplicates
import pandas as pd
data = {
    'ID': [101, 102, 103, 101, 104, 102, 105],
    'Product': ['A', 'B', 'C', 'A', 'D', 'B', 'E'],
    'Price': [10, 20, 30, 10, 40, 20, 50],
    'Date': ['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-01', '2024-01-04', '2024-01-02', '2024-01-05']
}
df = pd.DataFrame(data)
df

    ID Product  Price        Date
0  101       A     10  2024-01-01
1  102       B     20  2024-01-02
2  103       C     30  2024-01-03
3  101       A     10  2024-01-01
4  104       D     40  2024-01-04
5  102       B     20  2024-01-02
6  105       E     50  2024-01-05

In [44]:
#Task 1: Use .duplicated() to identify duplicate rows in the entire DataFrame. 
# How many duplicate rows are there?
dupes = df.duplicated()
dupes.sum()

np.int64(2)

In [45]:
#Task 2: Drop duplicate rows and assign the result to df_unique. Print the cleaned DataFrame.

df_unique = df.drop_duplicates()
df_unique

    ID Product  Price        Date
0  101       A     10  2024-01-01
1  102       B     20  2024-01-02
2  103       C     30  2024-01-03
4  104       D     40  2024-01-04
6  105       E     50  2024-01-05

In [46]:
#Task 3: Identify duplicates based only on the ID column (ignore other columns). 
# How many duplicate IDs exist?

id_dupes = df.duplicated(subset=['ID'])
id_dupes.sum()

np.int64(2)

In [49]:
#Task 4: Drop duplicates based on the ID column, but keep the last occurrence of each ID. 
# Print the result.

id_dupes = df.drop_duplicates(subset=['ID'], keep='last')
id_dupes

    ID Product  Price        Date
2  103       C     30  2024-01-03
3  101       A     10  2024-01-01
4  104       D     40  2024-01-04
5  102       B     20  2024-01-02
6  105       E     50  2024-01-05

In [50]:
"""Task 5 (Bonus): Find all rows where both Product and Price are duplicated 
(i.e., same product sold at same price on potentially different dates). 
Drop them, keeping the first occurrence.
"""
result = df.drop_duplicates(subset=['Product', 'Price'], keep='first')
result

    ID Product  Price        Date
0  101       A     10  2024-01-01
1  102       B     20  2024-01-02
2  103       C     30  2024-01-03
4  104       D     40  2024-01-04
6  105       E     50  2024-01-05