In [2]:
#Day 1, Topic 4: Inspecting Data – Essential Methods
import pandas as pd

In [3]:
import pandas as pd

data = {
    'Name': ['Faizan', 'Ali', 'Usman', 'Arslan', 'Rohan'],
    'Age': [25, 30, 35, 28, None],
    'Salary': [50000, 60000, 70000, 55000, 65000],
    'Department': ['HR', 'IT', 'IT', 'HR', 'Finance']
}
df = pd.DataFrame(data)

In [4]:
df

     Name   Age  Salary Department
0  Faizan  25.0   50000         HR
1     Ali  30.0   60000         IT
2   Usman  35.0   70000         IT
3  Arslan  28.0   55000         HR
4   Rohan   NaN   65000    Finance

In [5]:
print(df.head(2))

print(df.tail(2))

     Name   Age  Salary Department
0  Faizan  25.0   50000         HR
1     Ali  30.0   60000         IT
     Name   Age  Salary Department
3  Arslan  28.0   55000         HR
4   Rohan   NaN   65000    Finance

In [8]:
print(df.shape)
print(df.columns)
print(df.index)

(5, 4)
Index(['Name', 'Age', 'Salary', 'Department'], dtype='object')
RangeIndex(start=0, stop=5, step=1)

In [9]:
print(df.dtypes)

print(df.info())

Name           object
Age           float64
Salary          int64
Department     object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         4 non-null      float64
 2   Salary      5 non-null      int64
 3   Department  5 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes
None

In [10]:
print(df.describe())

             Age       Salary
count   4.000000      5.00000
mean   29.500000  60000.00000
std     4.203173   7905.69415
min    25.000000  50000.00000
25%    27.250000  55000.00000
50%    29.000000  60000.00000
75%    31.250000  65000.00000
max    35.000000  70000.00000

In [12]:
print(df.describe(include='object'))

          Name Department
count        5          5
unique       5          3
top     Faizan         HR
freq         1          2

In [13]:
print(df['Department'].value_counts())

Department
HR         2
IT         2
Finance    1
Name: count, dtype: int64

In [14]:
print(df.nunique())

Name          5
Age           4
Salary        5
Department    3
dtype: int64

In [15]:
#Practical Activity: Topic 4
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Age': [25, 30, 35, 28, None],
    'Salary': [50000, 60000, 70000, 55000, 65000],
    'Department': ['HR', 'IT', 'IT', 'HR', 'Finance']
}
df = pd.DataFrame(data)

In [16]:
df

      Name   Age  Salary Department
0    Alice  25.0   50000         HR
1      Bob  30.0   60000         IT
2  Charlie  35.0   70000         IT
3    Diana  28.0   55000         HR
4      Eve   NaN   65000    Finance

In [17]:
"""Task 1: Quick Overview
Print the last 3 rows.
Print the shape."""

print(df.tail(3))
print(df.shape)

      Name   Age  Salary Department
2  Charlie  35.0   70000         IT
3    Diana  28.0   55000         HR
4      Eve   NaN   65000    Finance
(5, 4)

In [22]:
"""Task 2: Column Information
Print the column names.
Print the data types.
"""

print(df.columns.tolist())
print(df.dtypes)

['Name', 'Age', 'Salary', 'Department']
Name           object
Age           float64
Salary          int64
Department     object
dtype: object

In [23]:
"""Task 3: Missing Value Check
Use .info() to identify which column has missing values and how many.
"""
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         4 non-null      float64
 2   Salary      5 non-null      int64
 3   Department  5 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes
None

In [24]:
"""Task 4: Numeric Summary
Print summary statistics for numeric columns.
What is the median age?"""
print(df.describe())
print(df['Age'].median())

             Age       Salary
count   4.000000      5.00000
mean   29.500000  60000.00000
std     4.203173   7905.69415
min    25.000000  50000.00000
25%    27.250000  55000.00000
50%    29.000000  60000.00000
75%    31.250000  65000.00000
max    35.000000  70000.00000
29.0

In [26]:
"""Task 5: Categorical Summary
How many unique departments are there?
Which department appears most frequently, and how many times?
"""

print(df['Department'].nunique())
top_dept = df['Department'].value_counts().idxmax()
top_freq = df['Department'].value_counts().max()
print(f"Most frequent department: '{top_dept}' appears {top_freq} times.")

3
Most frequent department: 'HR' appears 2 times.

In [27]:
"""Task 6: Value Counts
Use .value_counts() on the 'Department' column to see the distribution."""

print(df['Department'].value_counts())

Department
HR         2
IT         2
Finance    1
Name: count, dtype: int64