In [79]:
#Day 1, Topic 3: The DataFrame Object – Deep Dive
import pandas as pd
import numpy as np

In [80]:
#From a dictionary of lists (most common):

data = {
    'Name': ['Faizan', 'Ali', 'Rohan'],
    'Age': [22, 18, 20],
    'Salary': [50000, 67000, 32000]
}

df = pd.DataFrame(data)
print(df)

     Name  Age  Salary
0  Faizan   22   50000
1     Ali   18   67000
2   Rohan   20   32000

In [81]:
#From a list of dictionaries (each dict = one row):

data = [
    {'Name': 'Faizan', 'Age': 18, 'Salary': 40000},
    {'Name': 'Rohan', 'Age': 19, 'Salary': 60000},
    {'Name': 'Ali', 'Age': 17, 'Salary': 50000},
]

df = pd.DataFrame(data)

print(df)

     Name  Age  Salary
0  Faizan   18   40000
1   Rohan   19   60000
2     Ali   17   50000

In [82]:
#From a list of lists with explicit column names:

data = [
    ['Faizan', 18, 40000],
    ['Usman', 19, 50000],
    ['Rohan', 17, 30000],
]

df = pd.DataFrame(data, columns=['Name', 'Age', 'Salary'])


print(df)

     Name  Age  Salary
0  Faizan   18   40000
1   Usman   19   50000
2   Rohan   17   30000

In [83]:
#From a dictionary of Series (useful when you already have Series):
s1 = pd.Series(['Faizan', 'Arslan', 'Rohan'], name='Name')
s2 = pd.Series([18, 17, 19], name='Age')
s3 = pd.Series([40000, 50000, 43000], name='Salary')

df = pd.DataFrame({'Name': s1, 'Age': s2, 'Salary': s3})
print(df)

     Name  Age  Salary
0  Faizan   18   40000
1  Arslan   17   50000
2   Rohan   19   43000

In [84]:
#Reading Data from a File (CSV)
df = pd.read_csv('listings.csv')

In [85]:
#Inspecting a DataFrame – Essential Methods
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'Salary': [50000, 60000, 70000, 55000],
    'Department': ['HR', 'IT', 'IT', 'HR']
})

print(df)

      Name  Age  Salary Department
0    Alice   25   50000         HR
1      Bob   30   60000         IT
2  Charlie   35   70000         IT
3    Diana   28   55000         HR

In [86]:
#Methods
df.head()
df.head(2)
df.tail()
df.tail(3)
df.shape
df.columns
df.index
df.dtypes
df.info() 
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      object
 1   Age         4 non-null      int64
 2   Salary      4 non-null      int64
 3   Department  4 non-null      object
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

             Age        Salary
count   4.000000      4.000000
mean   29.500000  58750.000000
std     4.203173   8539.125638
min    25.000000  50000.000000
25%    27.250000  53750.000000
50%    29.000000  57500.000000
75%    31.250000  62500.000000
max    35.000000  70000.000000

In [87]:
#Accessing Columns
#Single column (returns a Series):
df['Name']
df.Name

0      Alice
1        Bob
2    Charlie
3      Diana
Name: Name, dtype: object

In [88]:
#Multiple columns (returns a DataFrame):
df[['Name', 'Salary']]

      Name  Salary
0    Alice   50000
1      Bob   60000
2  Charlie   70000
3    Diana   55000

In [89]:
#Creating a new column:
df['Bonus'] = df['Salary'] * 0.10
df['Start_date'] = '2024-01-01'
print(df)

      Name  Age  Salary Department   Bonus  Start_date
0    Alice   25   50000         HR  5000.0  2024-01-01
1      Bob   30   60000         IT  6000.0  2024-01-01
2  Charlie   35   70000         IT  7000.0  2024-01-01
3    Diana   28   55000         HR  5500.0  2024-01-01

In [90]:
#Modifying an existing column:
df['Salary'] = df['Salary'] * 1.05
print(df)

      Name  Age   Salary Department   Bonus  Start_date
0    Alice   25  52500.0         HR  5000.0  2024-01-01
1      Bob   30  63000.0         IT  6000.0  2024-01-01
2  Charlie   35  73500.0         IT  7000.0  2024-01-01
3    Diana   28  57750.0         HR  5500.0  2024-01-01

In [91]:
print(df)

      Name  Age   Salary Department   Bonus  Start_date
0    Alice   25  52500.0         HR  5000.0  2024-01-01
1      Bob   30  63000.0         IT  6000.0  2024-01-01
2  Charlie   35  73500.0         IT  7000.0  2024-01-01
3    Diana   28  57750.0         HR  5500.0  2024-01-01

In [92]:
#Boolean Indexing on DataFrames
mask = df['Age'] > 30
older_employees = df[mask]
print(older_employees)

      Name  Age   Salary Department   Bonus  Start_date
2  Charlie   35  73500.0         IT  7000.0  2024-01-01

In [93]:
#Multiple conditions – use & (AND), | (OR), and parentheses.

df[(df['Age'] > 30) & (df['Department'] == 'IT')]

      Name  Age   Salary Department   Bonus  Start_date
2  Charlie   35  73500.0         IT  7000.0  2024-01-01

In [94]:
#The .loc and .iloc Accessors
df.loc[0, 'Name']
df.iloc[0, 1]
df.loc[0:2, ['Name', 'Department']]
df.iloc[0:3, 1:4]

   Age   Salary Department
0   25  52500.0         HR
1   30  63000.0         IT
2   35  73500.0         IT

In [95]:
#Practical Activity: Topic 3
import pandas as pd

data = {
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headphones'],
    'Category': ['Electronics', 'Accessories', 'Accessories', 'Electronics', 'Accessories'],
    'Price': [1200, 25, 75, 300, 80],
    'Quantity': [5, 50, 30, 10, 40],
    'Rating': [4.5, 4.2, 4.7, 4.3, 4.8]
}
df = pd.DataFrame(data)

In [96]:
df

      Product     Category  Price  Quantity  Rating
0      Laptop  Electronics   1200         5     4.5
1       Mouse  Accessories     25        50     4.2
2    Keyboard  Accessories     75        30     4.7
3     Monitor  Electronics    300        10     4.3
4  Headphones  Accessories     80        40     4.8

In [97]:
"""Task 1: Basic Inspection
Print the first 3 rows.
Print the shape (rows, columns).
Print the column names.
Print the data types of all columns.
Print summary statistics for numeric columns only."""
print("\nThe first 3 rows from data are given below:\n", df.head(3))
print("\nThe shape of dataset is:", df.shape)
print("\nDisplaying the column names from dataset: ", df.columns)
print("\nStats for numeric columns:\n", df.describe())

The first 3 rows from data are given below:
     Product     Category  Price  Quantity  Rating
0    Laptop  Electronics   1200         5     4.5
1     Mouse  Accessories     25        50     4.2
2  Keyboard  Accessories     75        30     4.7

The shape of dataset is: (5, 5)

Displaying the column names from dataset:  Index(['Product', 'Category', 'Price', 'Quantity', 'Rating'], dtype='object')

Stats for numeric columns:
              Price   Quantity    Rating
count     5.000000   5.000000  5.000000
mean    336.000000  27.000000  4.500000
std     494.512386  19.235384  0.254951
min      25.000000   5.000000  4.200000
25%      75.000000  10.000000  4.300000
50%      80.000000  30.000000  4.500000
75%     300.000000  40.000000  4.700000
max    1200.000000  50.000000  4.800000

In [98]:
df

      Product     Category  Price  Quantity  Rating
0      Laptop  Electronics   1200         5     4.5
1       Mouse  Accessories     25        50     4.2
2    Keyboard  Accessories     75        30     4.7
3     Monitor  Electronics    300        10     4.3
4  Headphones  Accessories     80        40     4.8

In [99]:
"""Task 2: Column Operations
Create a new column 'Revenue' which is Price * Quantity.
Increase all prices by 5% (update the 'Price' column in‑place).
Drop the 'Rating' column and assign the result back to df."""
df['Revenue'] = df['Price'] * df['Quantity']
df['Price'] *= 1.05
df = df.drop('Rating', axis=1)
print("\nDataset after adding a new column, increase an existing column and removing the rating column:\n", df)

Dataset after adding a new column, increase an existing column and removing the rating column:
       Product     Category    Price  Quantity  Revenue
0      Laptop  Electronics  1260.00         5     6000
1       Mouse  Accessories    26.25        50     1250
2    Keyboard  Accessories    78.75        30     2250
3     Monitor  Electronics   315.00        10     3000
4  Headphones  Accessories    84.00        40     3200

In [100]:
df

      Product     Category    Price  Quantity  Revenue
0      Laptop  Electronics  1260.00         5     6000
1       Mouse  Accessories    26.25        50     1250
2    Keyboard  Accessories    78.75        30     2250
3     Monitor  Electronics   315.00        10     3000
4  Headphones  Accessories    84.00        40     3200

In [101]:
"""Task 3: Boolean Filtering
Create a Boolean mask for products where Category is 'Accessories'.
Use that mask to display only accessory products.
Display products where Price is greater than 100 and Quantity is less than 20."""
mask = (df['Category'] == 'Accessories')
accessory_products = df[mask]
print("\nAccessory product data set:\n", accessory_products)
price_mask = (df['Price'] > 100) & (df['Quantity'] < 20)
print("\nDisplaing products where Price is greater than 100 and Quantity is less than 20:\n", df[price_mask])

Accessory product data set:
       Product     Category  Price  Quantity  Revenue
1       Mouse  Accessories  26.25        50     1250
2    Keyboard  Accessories  78.75        30     2250
4  Headphones  Accessories  84.00        40     3200

Displaing products where Price is greater than 100 and Quantity is less than 20:
    Product     Category   Price  Quantity  Revenue
0   Laptop  Electronics  1260.0         5     6000
3  Monitor  Electronics   315.0        10     3000

In [102]:
df

      Product     Category    Price  Quantity  Revenue
0      Laptop  Electronics  1260.00         5     6000
1       Mouse  Accessories    26.25        50     1250
2    Keyboard  Accessories    78.75        30     2250
3     Monitor  Electronics   315.00        10     3000
4  Headphones  Accessories    84.00        40     3200

In [103]:
"""Task 4: Access with .loc and .iloc
Using .loc, select the row with index label 2 and the column 'Product'.
Using .iloc, select the first row and the last column (position‑based).
Using .loc, select rows 0 through 2 (inclusive) and columns 'Product' and 'Price'.
"""
print("Selecting the row with index label 2 and the column 'Product': ", df.loc[2, 'Product'])
print("Selecting the first row and the last column: ", df.iloc[0, 4])
print("\nSelecting rows 0 through 2 (inclusive) and columns 'Product' and 'Price':\n",df.loc[0:2, ['Product']])

Selecting the row with index label 2 and the column 'Product':  Keyboard
Selecting the first row and the last column:  6000

Selecting rows 0 through 2 (inclusive) and columns 'Product' and 'Price':
     Product
0    Laptop
1     Mouse
2  Keyboard

In [104]:
df

      Product     Category    Price  Quantity  Revenue
0      Laptop  Electronics  1260.00         5     6000
1       Mouse  Accessories    26.25        50     1250
2    Keyboard  Accessories    78.75        30     2250
3     Monitor  Electronics   315.00        10     3000
4  Headphones  Accessories    84.00        40     3200

In [105]:
"""Task 5: Create a DataFrame from Scratch
Create a list of lists: [['Ali', 22], ['Sara', 24], ['Omar', 21]].
Convert it to a DataFrame with columns 'Name' and 'Age'.
Set the 'Name' column as the index (use df.set_index('Name', inplace=True)).
Print the resulting DataFrame.
"""

data = [
    ['Ali', 22],
    ['Faizan', 18],
    ['Omar', 21]
]

df = pd.DataFrame(data, columns=['Name', 'Age'])

print(df)

     Name  Age
0     Ali   22
1  Faizan   18
2    Omar   21

In [106]:
df.set_index('Name', inplace=True)

In [107]:
df

        Age
Name
Ali      22
Faizan   18
Omar     21