In [40]:
#Day 5, Topic 3: Joining with .join()

import pandas as pd

df = pd.read_csv('titanic.csv')

In [41]:
#Basic Index‑Based Join
passengers = df[['Name', 'Sex', 'Age']].set_index(df['PassengerId'])
tickets = df[['Pclass', 'Fare', 'Embarked']].set_index(df['PassengerId'])

result = passengers.join(tickets)

result.head()

,Name,Sex,Age,Pclass,Fare,Embarked
PassengerId,,,,,,
1,"Braund, Mr. Owen Harris",male,22.0,3,7.2500,S
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,71.2833,C
3,"Heikkinen, Miss. Laina",female,26.0,3,7.9250,S
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,53.1000,S
5,"Allen, Mr. William Henry",male,35.0,3,8.0500,S

In [42]:
#Specifying Join Type with how
inner_joined = passengers.join(tickets, how='inner')
inner_joined.shape

(891, 6)

In [43]:
#Joining on a Column Instead of Index
passenger_reset = passengers.reset_index()
ticket_reset = tickets.reset_index()

joined = passenger_reset.join(ticket_reset.set_index('PassengerId'), on='PassengerId')

joined.head()

,PassengerId,Name,Sex,Age,Pclass,Fare,Embarked
0,1,"Braund, Mr. Owen Harris",male,22.0,3,7.2500,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,71.2833,C
2,3,"Heikkinen, Miss. Laina",female,26.0,3,7.9250,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,53.1000,S
4,5,"Allen, Mr. William Henry",male,35.0,3,8.0500,S

In [44]:
#Handling Overlapping Column Names
#passengers['Score'] = 100
#tickets['Score'] = 200

#joined = passengers.join(tickets, lsuffix='_passenger', rsuffix='_ticket')
#joined.columns

In [45]:
#Joining Multiple DataFrames at Once
survival = df[['Survived']].set_index(df['PassengerId'])

result = passengers.join([tickets, survival])
result.head()

,Name,Sex,Age,Pclass,Fare,Embarked,Survived
PassengerId,,,,,,,
1,"Braund, Mr. Owen Harris",male,22.0,3,7.2500,S,0
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,71.2833,C,1
3,"Heikkinen, Miss. Laina",female,26.0,3,7.9250,S,1
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,53.1000,S,1
5,"Allen, Mr. William Henry",male,35.0,3,8.0500,S,0

In [46]:
#Practice Activity: .join()
import pandas as pd
df = pd.read_csv('titanic.csv')
# Create three DataFrames, each indexed by 'PassengerId'
df1 = df[['Name', 'Sex']].set_index(df['PassengerId'])
df2 = df[['Age', 'Fare']].set_index(df['PassengerId'])
df3 = df[['Survived', 'Pclass']].set_index(df['PassengerId'])

In [47]:
#Task 1: Use .join() to combine df1 and df2 (left join). Display the first 3 rows.

result = df1.join(df2, how='left')
result.head(3)

,Name,Sex,Age,Fare
PassengerId,,,,
1,"Braund, Mr. Owen Harris",male,22.0,7.2500
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833
3,"Heikkinen, Miss. Laina",female,26.0,7.9250

In [48]:
#Task 2: Join all three DataFrames (df1, df2, df3) in a single .join() call. Use an inner join.

result = df1.join([df2, df3], how='inner')
result.head()

,Name,Sex,Age,Fare,Survived,Pclass
PassengerId,,,,,,
1,"Braund, Mr. Owen Harris",male,22.0,7.2500,0,3
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,1,1
3,"Heikkinen, Miss. Laina",female,26.0,7.9250,1,3
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,1,1
5,"Allen, Mr. William Henry",male,35.0,8.0500,0,3

In [49]:
"""Task 3: Create a new DataFrame df4 that has the same index as df1 but contains a column 
'Deck' (first letter of Cabin). Then join df4 to df1 and specify rsuffix='_Deck' 
to handle any duplicate columns (though there shouldn't be any, it's good practice). Display the result."""

df4 = pd.DataFrame({'Deck': df['Cabin'].str[0]}, index=df1.index)

result = df1.join(df4, rsuffix='_Deck')

result.head()

                                                          Name     Sex Deck
PassengerId
1                                      Braund, Mr. Owen Harris    male    C
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  NaN
3                                       Heikkinen, Miss. Laina  female    C
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  NaN
5                                     Allen, Mr. William Henry    male  NaN

In [50]:
"""Task 4 (Bonus): Reset the index of df1 and df2 so that PassengerId becomes a column. 
Now use .join() with the on parameter to join df2 
(after setting its index back to PassengerId) to df1. This demonstrates the column‑on‑index join."""

df1_reset = df1.reset_index()
df2_reset = df2.reset_index()

result = df1_reset.join(df2_reset.set_index('PassengerId'), on='PassengerId')
result.head()

,PassengerId,Name,Sex,Age,Fare
0,1,"Braund, Mr. Owen Harris",male,22.0,7.2500
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833
2,3,"Heikkinen, Miss. Laina",female,26.0,7.9250
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000
4,5,"Allen, Mr. William Henry",male,35.0,8.0500

In [51]:
#Day 5, Topic 4: Handling Duplicate Column Names

import pandas as pd

In [52]:
#Default Suffixes (_x and _y)
left = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Score': [85, 90, 78]
})

right = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Score': [88, 92, 80]
})

merged = pd.merge(left, right, on='ID')

merged

   ID   Name_x  Score_x   Name_y  Score_y
0   1    Alice       85    Alice       88
1   2      Bob       90      Bob       92
2   3  Charlie       78  Charlie       80

In [53]:
#Customizing Suffixes with suffixes
merged = pd.merge(left, right, on='ID', suffixes=('_Left', '_Right'))
merged.columns.tolist()

['ID', 'Name_Left', 'Score_Left', 'Name_Right', 'Score_Right']

In [54]:
#With .join():

left_joined = left.set_index('ID').join(right.set_index('ID'), lsuffix='_L', rsuffix='_R')
print(left_joined.columns.tolist())

['Name_L', 'Score_L', 'Name_R', 'Score_R']

In [55]:
#Dropping Duplicate Columns After Merge
merged = merged.drop(columns=['Name_Right', 'Score_Right'])
merged.columns.tolist()

['ID', 'Name_Left', 'Score_Left']

In [56]:
#Real Titanic Example
df = pd.read_csv('titanic.csv')
# Two DataFrames with overlapping 'Name' and 'Age' columns
passengers = df[['PassengerId', 'Name', 'Age', 'Sex']].copy()
age_backup = df[['PassengerId', 'Name', 'Age']].copy()
age_backup['Age'] = age_backup['Age'].fillna(30)  # Filled ages

merged = pd.merge(passengers, age_backup, on='PassengerId', suffixes=('_Original', '_Filled'))
merged.columns.tolist()

['PassengerId',
 'Name_Original',
 'Age_Original',
 'Sex',
 'Name_Filled',
 'Age_Filled']

In [57]:
#Preventing Duplicate Columns Before Merge
age_backup_renamed = age_backup.rename(columns={'Name': 'Name_backup', 'Age': 'Age_filled'})
merged = pd.merge(passengers, age_backup_renamed, on='PassengerId')

merged.columns.tolist()

['PassengerId', 'Name', 'Age', 'Sex', 'Name_backup', 'Age_filled']

In [58]:
#Practice Activity: Handling Duplicate Columns
import pandas as pd
df = pd.read_csv('titanic.csv')
# Create two overlapping DataFrames
df_a = df[['PassengerId', 'Name', 'Age', 'Fare']].iloc[:10].copy()
df_b = df[['PassengerId', 'Name', 'Pclass', 'Survived']].iloc[:10].copy()

In [59]:
#Task 1: Merge df_a and df_b on 'PassengerId'. Observe the default column names. Print the column list.

merged = pd.merge(df_a, df_b, on='PassengerId')
merged.columns.tolist()

['PassengerId', 'Name_x', 'Age', 'Fare', 'Name_y', 'Pclass', 'Survived']

In [60]:
#Task 2: Repeat the merge, but use suffixes=('_A', '_B') to clearly label the source DataFrame. Print the column list.

merged = pd.merge(df_a, df_b, on='PassengerId', suffixes=('_A', '_B'))
merged.columns.tolist()

['PassengerId', 'Name_A', 'Age', 'Fare', 'Name_B', 'Pclass', 'Survived']

In [61]:
#Task 3: Drop the duplicate Name column that came from df_b (i.e., 'Name_B'). Verify the remaining columns.
merged = merged.drop(columns=['Name_B'])
merged.columns.tolist()

['PassengerId', 'Name_A', 'Age', 'Fare', 'Pclass', 'Survived']

In [62]:
"""Task 4 (Bonus): Rename the columns in df_b before merging so that no duplicate column names exist. 
Specifically, rename 'Name' to 'Name_FromB' and 'Pclass' to 'Class'. Then perform the merge. 
This is the cleanest production approach."""

df_B_renamed = df_b.rename(columns={'Name': 'Name_FromB', 'Pclass': 'Class'})
merged = pd.merge(df_a, df_B_renamed, on='PassengerId')
merged.columns.tolist()

['PassengerId', 'Name', 'Age', 'Fare', 'Name_FromB', 'Class', 'Survived']