In [1]:
#Day 5, Topic 1: Concatenating with pd.concat()
import pandas as pd

df = pd.read_csv('titanic.csv')

In [3]:
#Vertical Concatenation (axis=0 – The Default)
df1 = df.iloc[:5]
df2 = df.iloc[5:10]

result = pd.concat([df1, df2], axis=0)
print(result.shape)
result

(10, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [4]:
result_clean = pd.concat([df1, df2], ignore_index=True)

result_clean.index

RangeIndex(start=0, stop=10, step=1)

In [5]:
#Horizontal Concatenation (axis=1)
df_left = df[['Name', 'Age', 'Sex']].iloc[:5]
df_right = df[['Fare', 'Embarked']].iloc[:5]

result = pd.concat([df_left, df_right], axis=1)
result

,Name,Age,Sex,Fare,Embarked
0,"Braund, Mr. Owen Harris",22.0,male,7.2500,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,female,71.2833,C
2,"Heikkinen, Miss. Laina",26.0,female,7.9250,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,female,53.1000,S
4,"Allen, Mr. William Henry",35.0,male,8.0500,S

In [6]:
#Adding Keys for MultiIndex (keys Parameter)
southampton = df[df['Embarked'] == 'S'].head(3)
cherbourg = df[df['Embarked'] == 'C'].head(3)

result = pd.concat([southampton, cherbourg], keys=['southampton', 'cherbourg'])

result

                PassengerId  Survived  Pclass  \
southampton 0             1         0       3
            2             3         1       3
            3             4         1       1
cherbourg   1             2         1       1
            9            10         1       2
            19           20         1       3

                                                             Name     Sex  \
southampton 0                             Braund, Mr. Owen Harris    male
            2                              Heikkinen, Miss. Laina  female
            3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
cherbourg   1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female
            9                 Nasser, Mrs. Nicholas (Adele Achem)  female
            19                            Masselmani, Mrs. Fatima  female

                 Age  SibSp  Parch            Ticket     Fare Cabin Embarked
southampton 0   22.0      1      0         A/5 21171   7.2500   NaN        S
            2   26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
            3   35.0      1      0            113803  53.1000  C123        S
cherbourg   1   38.0      1      0          PC 17599  71.2833   C85        C
            9   14.0      1      0            237736  30.0708   NaN        C
            19   NaN      0      0              2649   7.2250   NaN        C

In [7]:
#Practice Activity: pd.concat()
import pandas as pd
df = pd.read_csv('titanic.csv')
# Create three separate DataFrames
df_first = df[df['Pclass'] == 1].iloc[:3]   # First 3 rows of 1st class
df_second = df[df['Pclass'] == 2].iloc[:3]  # First 3 rows of 2nd class
df_third = df[df['Pclass'] == 3].iloc[:3]   # First 3 rows of 3rd class

In [17]:
# Task 1: Vertically concatenate df_first, df_second, df_third in that order.
# Use ignore_index=True for a clean index.
# What is the shape of the result?
result = pd.concat([df_first, df_second, df_third], axis=0, ignore_index=True)
result.shape

(9, 12)

In [18]:
# Task 2: Concatenate the same three DataFrames vertically, but this time use 
# the keys parameter with labels ['First', 'Second', 'Third'].
# Use .loc to select only the rows from the 'Second' group.
concat = pd.concat([df_first, df_second, df_third], axis=0, keys=['First', 'Second', 'Third'])
concat.loc['Second']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S

In [19]:
# Task 3: Split df into two horizontal halves:
# left_half: columns 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket'
# right_half: columns 'Fare', 'Cabin', 'Embarked'
# Take the first 5 rows of each and concatenate them horizontally (axis=1).
# Verify that the rows align correctly.
left_cols = ['Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket']
right_cols = ['Fare', 'Cabin', 'Embarked']

df_1 = df.loc[:4, left_cols]
df_2 = df.loc[:4, right_cols]

result = pd.concat([df_1, df_2], axis=1)
result

,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [20]:
# Task 4 (Bonus): Create a function that takes a list of DataFrames and returns 
# a single DataFrame concatenated vertically, but only keeps columns that are 
# present in ALL of the input DataFrames

def concat_dataframes(df_1, df_2):
    return pd.concat([df_1, df_2], axis=0, join='inner')

df_1 = df.iloc[:5]
df_2 = df.iloc[5: 10]

result = concat_dataframes(df_1=df_1, df_2=df_2)
result

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [21]:
df_a = pd.DataFrame({'A': [1,2], 'B': [3,4]})
df_b = pd.DataFrame({'B': [5,6], 'C': [7,8]})
pd.concat([df_a, df_b], join='inner')   # Only column 'B' is kept

   B
0  3
1  4
0  5
1  6

In [22]:
#Day 5, Topic 2: Merging with pd.merge()

import pandas as pd

df = pd.read_csv('titanic.csv')

In [23]:
#The Two DataFrames We'll Join
passengers = df[['PassengerId', 'Name', 'Sex', 'Age']].copy()

tickets = df[['PassengerId', 'Pclass', 'Fare', 'Embarked']].copy()

tickets = tickets.drop([2, 5, 10])

print(passengers.shape)
print(tickets.shape)

(891, 4)
(888, 4)

In [25]:
#Inner Join (how='inner')
inner_joined = pd.merge(passengers, tickets, on='PassengerId', how='inner')
print(inner_joined.shape)
inner_joined.head()

(888, 7)

,PassengerId,Name,Sex,Age,Pclass,Fare,Embarked
0,1,"Braund, Mr. Owen Harris",male,22.0,3,7.2500,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,71.2833,C
2,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,53.1000,S
3,5,"Allen, Mr. William Henry",male,35.0,3,8.0500,S
4,7,"McCarthy, Mr. Timothy J",male,54.0,1,51.8625,S

In [26]:
#Left Join (how='left')
left_joined = pd.merge(passengers, tickets, on='PassengerId', how='left')
print(left_joined.shape)
left_joined.head()

(891, 7)

,PassengerId,Name,Sex,Age,Pclass,Fare,Embarked
0,1,"Braund, Mr. Owen Harris",male,22.0,3.0,7.2500,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,71.2833,C
2,3,"Heikkinen, Miss. Laina",female,26.0,NaN,NaN,NaN
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,53.1000,S
4,5,"Allen, Mr. William Henry",male,35.0,3.0,8.0500,S

In [28]:
#Right Join (how='right')
right_joined = pd.merge(passengers, tickets, on='PassengerId', how='right')
print(right_joined.shape)
right_joined.head()

(888, 7)

,PassengerId,Name,Sex,Age,Pclass,Fare,Embarked
0,1,"Braund, Mr. Owen Harris",male,22.0,3,7.2500,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,71.2833,C
2,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,53.1000,S
3,5,"Allen, Mr. William Henry",male,35.0,3,8.0500,S
4,7,"McCarthy, Mr. Timothy J",male,54.0,1,51.8625,S

In [29]:
#Outer Join (how='outer')
outer_joined = pd.merge(passengers, tickets, on='PassengerId', how='outer')
print(outer_joined.shape)

(891, 7)

In [30]:
#Merging on Different Column Names
tickets_renamed = tickets.rename(columns={'PassengerId': 'PID'})

merged = pd.merge(passengers, tickets_renamed, left_on='PassengerId', right_on='PID', how='inner')
merged.head()

,PassengerId,Name,Sex,Age,PID,Pclass,Fare,Embarked
0,1,"Braund, Mr. Owen Harris",male,22.0,1,3,7.2500,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,2,1,71.2833,C
2,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,4,1,53.1000,S
3,5,"Allen, Mr. William Henry",male,35.0,5,3,8.0500,S
4,7,"McCarthy, Mr. Timothy J",male,54.0,7,1,51.8625,S

In [32]:
#Merging on Multiple Columns
# Example: Create a surrogate key
passengers['Deck'] = passengers['Name'].str[0]
tickets['Deck'] = tickets['Embarked']  # Not logical, just for demo

merged_multi = pd.merge(passengers, tickets, on=['PassengerId', 'Deck'], how='inner')
merged_multi.head()

,PassengerId,Name,Sex,Age,Deck,Pclass,Fare,Embarked
0,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,C,1,71.2833,C
1,13,"Saundercock, Mr. William Henry",male,20.0,S,3,8.0500,S
2,24,"Sloper, Mr. William Thompson",male,28.0,S,1,35.5000,S
3,64,"Skoog, Master. Harald",male,4.0,S,3,27.9000,S
4,74,"Chronopoulos, Mr. Apostolos",male,26.0,C,3,14.4542,C

In [33]:
#Handling Duplicate Column Names
merged = pd.merge(passengers, tickets, on='PassengerId', suffixes=('_Passenger', '_Ticket'))

merged.columns

Index(['PassengerId', 'Name', 'Sex', 'Age', 'Deck_Passenger', 'Pclass', 'Fare',
       'Embarked', 'Deck_Ticket'],
      dtype='object')

In [34]:
#Practice Activity: pd.merge()
import pandas as pd

df = pd.read_csv('titanic.csv')

#The Two DataFrames We'll Join
passengers = df[['PassengerId', 'Name', 'Sex', 'Age']].copy()

tickets = df[['PassengerId', 'Pclass', 'Fare', 'Embarked']].copy()

tickets = tickets.drop([2, 5, 10])

print(passengers.shape)
print(tickets.shape)

(891, 4)
(888, 4)

In [36]:
#Task 1: Perform an inner join on PassengerId. How many rows are in the result? Why is it less than 891?

inner_joined = pd.merge(passengers, tickets, on='PassengerId', how='inner')

len(inner_joined)

888

In [40]:
"""Task 2: Perform a left join on PassengerId. Find a passenger who has missing ticket information. 
Display their PassengerId, Name, and Fare."""

left_joined = pd.merge(passengers, tickets, on='PassengerId', how='left')

missing_tickets = left_joined[left_joined['Fare'].isna()]

if not missing_tickets.empty:
    result = missing_tickets[['PassengerId', 'Name', 'Fare']].head(1)
    print(result)
else:
    print("No passengers found with missing ticket information.")

   PassengerId                    Name  Fare
2            3  Heikkinen, Miss. Laina   NaN

In [44]:
"""Task 3: Rename the PassengerId column in tickets to 'PID'. Then perform an inner join using left_on='PassengerId' 
and right_on='PID'. Drop the duplicate 'PID' column from the result.
"""

tickets_renamed = tickets.rename(columns={'PassengerId': 'PID'})

inner_merged = pd.merge(passengers, tickets_renamed, left_on='PassengerId', right_on='PID', how='inner')
inner_merged.drop('PID', axis=1)

,PassengerId,Name,Sex,Age,Pclass,Fare,Embarked
0,1,"Braund, Mr. Owen Harris",male,22.0,3,7.2500,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,71.2833,C
2,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,53.1000,S
3,5,"Allen, Mr. William Henry",male,35.0,3,8.0500,S
4,7,"McCarthy, Mr. Timothy J",male,54.0,1,51.8625,S
...,...,...,...,...,...,...,...
883,887,"Montvila, Rev. Juozas",male,27.0,2,13.0000,S
884,888,"Graham, Miss. Margaret Edith",female,19.0,1,30.0000,S
885,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,3,23.4500,S
886,890,"Behr, Mr. Karl Howell",male,26.0,1,30.0000,C
887,891,"Dooley, Mr. Patrick",male,32.0,3,7.7500,Q

In [45]:
"""Task 4: Suppose you want to keep only passengers who DO NOT have a matching ticket record. 
How can you achieve this using a merge? (Hint: how='left' and then filter for NaN, 
or use the indicator=True parameter.)"""

left_joined = pd.merge(passengers, tickets, on='PassengerId', how='left')
no_ticket = left_joined[left_joined['Fare'].isna()]
no_ticket[['PassengerId', 'Name']].head()

    PassengerId                             Name
2             3           Heikkinen, Miss. Laina
5             6                 Moran, Mr. James
10           11  Sandstrom, Miss. Marguerite Rut

In [46]:
"""Task 5 (Bonus): Use pd.merge() with indicator=True to add a '_merge' column showing the 
source of each row ('both', 'left_only', 'right_only'). Then count how many rows came from each source."""

merged_indicator = pd.merge(passengers, tickets, on='PassengerId', how='outer', indicator=True)
merged_indicator['_merge'].value_counts()

_merge
both          888
left_only       3
right_only      0
Name: count, dtype: int64