In [1]:
#Day 7, Topic 3: .pivot_table()
import pandas as pd

In [2]:
#Basic .pivot_table()
df = pd.read_csv('titanic.csv')
# Average Fare by Pclass (rows) and Embarked (columns)
pivot = pd.pivot_table(df, values='Fare', index='Pclass', columns='Embarked', aggfunc='mean')
pivot

Embarked           C          Q          S
Pclass
1         104.718529  90.000000  70.364862
2          25.358335  12.350000  20.327439
3          11.214083  11.183393  14.644083

In [4]:
#Multiple Aggregation Functions
pivot_mulit = pd.pivot_table(df, values='Fare', index='Pclass', columns='Embarked', aggfunc=['mean', 'median', 'count'])
pivot_mulit

                mean                         median               count      \
Embarked           C          Q          S        C      Q      S     C   Q
Pclass
1         104.718529  90.000000  70.364862  78.2667  90.00  52.00    85   2
2          25.358335  12.350000  20.327439  24.0000  12.35  13.50    17   3
3          11.214083  11.183393  14.644083   7.8958   7.75   8.05    66  72


Embarked    S
Pclass
1         127
2         164
3         353

In [6]:
#Multiple values Columns
pivot_multi_col = pd.pivot_table(df, values=['Fare', 'Age'], index='Pclass', columns='Sex', aggfunc={'Fare': 'mean', 'Age': 'median'})
pivot_multi_col

          Age              Fare
Sex    female  male      female       male
Pclass
1        35.0  40.0  106.125798  67.226127
2        28.0  30.0   21.970121  19.741782
3        21.5  25.0   16.118810  12.661633

In [7]:
#Margins (Totals)
pivot_margins = pd.pivot_table(df, values='Survived', index='Pclass', columns='Sex', aggfunc='mean', margins=True, margins_name='Total')
pivot_margins

Sex       female      male     Total
Pclass
1       0.968085  0.368852  0.629630
2       0.921053  0.157407  0.472826
3       0.500000  0.135447  0.242363
Total   0.742038  0.188908  0.383838

In [9]:
#Filling Missing Values
pivot_filled = pd.pivot_table(df, values='Fare', index='Pclass', columns='Embarked', aggfunc='sum', fill_value=0)
pivot_filled

Embarked          C         Q          S
Pclass
1         8901.0750  180.0000  8936.3375
2          431.0917   37.0500  3333.7000
3          740.1295  805.2043  5169.3613

In [10]:
#Grouping by Multiple Index/Columns
pivot_hier = pd.pivot_table(df, values='Fare', index=['Pclass', 'Sex'], columns='Embarked', aggfunc='mean')
pivot_hier

Embarked                C          Q          S
Pclass Sex
1      female  115.640309  90.000000  99.026910
       male     93.536707  90.000000  52.949947
2      female   25.268457  12.350000  21.912687
       male     25.421250  12.350000  19.232474
3      female   14.694926  10.307833  18.670077
       male      9.352237  11.924251  13.307149

In [11]:
#Practice Activity: .pivot_table() on Titanic
import pandas as pd
df = pd.read_csv('titanic.csv')

In [12]:
"""Task 1: Create a pivot table showing the average Age for each combination of Pclass 
(rows) and Survived (columns). Use aggfunc='mean'."""

pivot_age = pd.pivot_table(df, index='Pclass', columns='Survived', values='Age', aggfunc='mean')
pivot_age

Survived          0          1
Pclass
1         43.695312  35.368197
2         33.544444  25.901566
3         26.555556  20.646118

In [13]:
"""Task 2: Create a pivot table with index='Embarked' and columns='Sex', 
showing both the sum of Fare and the count of PassengerId. Use aggfunc={'Fare': 'sum', 'PassengerId': 'count'}."""

pivot_stats = pd.pivot_table(df, index='Embarked', columns='Sex', values=['Fare', 'PassengerId'], aggfunc={'Fare': 'sum', 'PassengerId': 'count'})
pivot_stats

               Fare            PassengerId
Sex          female       male      female male
Embarked
C         5487.3958  4584.9004          73   95
Q          454.8585   567.3958          36   41
S         7864.4085  9574.9903         203  441

In [15]:
#Task 3: Repeat Task 1, but add margins and fill NaN values with 0.

pivot_age = pd.pivot_table(df, index='Pclass', columns='Survived', values='Age', aggfunc='mean', margins=True, margins_name='Total', fill_value=0)
pivot_age

Survived          0          1      Total
Pclass
1         43.695312  35.368197  38.233441
2         33.544444  25.901566  29.877630
3         26.555556  20.646118  25.140620
Total     30.626179  28.343690  29.699118

In [19]:
"""Task 4 (Bonus): Create a pivot table with index=['Pclass', 'Sex'] and 
columns='Embarked', showing the maximum Fare. Then, using .loc, extract only the sub‑table for Pclass=1"""

pivot = pd.pivot_table(df, index=['Pclass', 'Sex'], columns='Embarked', values='Fare', aggfunc='max')
pivot.loc[1]

Embarked         C     Q      S
Sex
female    512.3292  90.0  263.0
male      512.3292  90.0  263.0

In [20]:
#Day 7, Topic 4: .stack() and .unstack()
import pandas as pd

In [21]:
#Creating a MultiIndex DataFrame to Work With
data = {
    'Region': ['North', 'North', 'South', 'South'],
    'Year': [2022, 2023, 2022, 2023],
    'Sales': [100, 120, 150, 170]
}
df = pd.DataFrame(data)

# Create a MultiIndex on Region and Year
df_multi = df.set_index(['Region', 'Year'])
print("Original MultiIndex DataFrame:")
df_multi

Original MultiIndex DataFrame:

             Sales
Region Year
North  2022    100
       2023    120
South  2022    150
       2023    170

In [22]:
unstacked = df_multi.unstack()
unstacked

       Sales
Year    2022 2023
Region
North    100  120
South    150  170

In [26]:
unstacked_region = df_multi.unstack(level=0)
unstacked_region

       Sales
Region North South
Year
2022     100   150
2023     120   170

In [27]:
#.stack() – Move Column Index to Rows
stacked_back = unstacked.stack()
stacked_back

C:\Users\Faizan Toheed\AppData\Local\Temp\ipykernel_6488\1748500519.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_back = unstacked.stack()

             Sales
Region Year
North  2022    100
       2023    120
South  2022    150
       2023    170

In [28]:
#Stacking/Unstacking with Multiple Levels
# Create a DataFrame with MultiIndex columns
cols = pd.MultiIndex.from_product([['Q1', 'Q2'], ['Units', 'Revenue']])
df_col_multi = pd.DataFrame([[10, 100, 12, 120],
                              [15, 150, 18, 180]],
                            index=['Product A', 'Product B'],
                            columns=cols)
print("DataFrame with MultiIndex columns:")
df_col_multi

DataFrame with MultiIndex columns:

             Q1            Q2
          Units Revenue Units Revenue
Product A    10     100    12     120
Product B    15     150    18     180

In [29]:
stacked_cols = df_col_multi.stack(level=1)
stacked_cols

C:\Users\Faizan Toheed\AppData\Local\Temp\ipykernel_6488\2044445028.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_cols = df_col_multi.stack(level=1)

                    Q1   Q2
Product A Revenue  100  120
          Units     10   12
Product B Revenue  150  180
          Units     15   18

In [31]:
#Real‑World Use Case – Titanic

df = pd.read_csv('titanic.csv')

# Create a pivot table with MultiIndex columns
pivot = pd.pivot_table(df, values='Fare', index='Pclass', columns=['Sex', 'Embarked'], aggfunc='mean')
print("Pivot table with MultiIndex columns:")
pivot

Pivot table with MultiIndex columns:

Sex           female                             male
Embarked           C          Q          S          C          Q          S
Pclass
1         115.640309  90.000000  99.026910  93.536707  90.000000  52.949947
2          25.268457  12.350000  21.912687  25.421250  12.350000  19.232474
3          14.694926  10.307833  18.670077   9.352237  11.924251  13.307149

In [32]:
stacked_sex = pivot.stack(level='Sex')
stacked_sex

C:\Users\Faizan Toheed\AppData\Local\Temp\ipykernel_6488\3526634861.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_sex = pivot.stack(level='Sex')

Embarked                C          Q          S
Pclass Sex
1      female  115.640309  90.000000  99.026910
       male     93.536707  90.000000  52.949947
2      female   25.268457  12.350000  21.912687
       male     25.421250  12.350000  19.232474
3      female   14.694926  10.307833  18.670077
       male      9.352237  11.924251  13.307149

In [34]:
#Practice Activity: .stack() and .unstack()
import pandas as pd
df = pd.read_csv('titanic.csv')

# Create a pivot table with MultiIndex rows
pivot = pd.pivot_table(df, values='Age', index=['Pclass', 'Sex'], columns='Survived', aggfunc='mean')
pivot

Survived               0          1
Pclass Sex
1      female  25.666667  34.939024
       male    44.581967  36.248000
2      female  36.000000  28.080882
       male    33.369048  16.022000
3      female  23.818182  19.329787
       male    27.255814  22.274211

In [41]:
#Task 1: Use .unstack() on pivot to move the Survived level from columns to rows. Observe the resulting structure.

unstacked = pivot.unstack()
unstacked

Survived          0                     1
Sex          female       male     female       male
Pclass
1         25.666667  44.581967  34.939024  36.248000
2         36.000000  33.369048  28.080882  16.022000
3         23.818182  27.255814  19.329787  22.274211

In [43]:
#Task 2: Take the result from Task 1 and use .stack() to return it to its original form.

stacked = unstacked.stack()
stacked

C:\Users\Faizan Toheed\AppData\Local\Temp\ipykernel_6488\1817287807.py:3: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked = unstacked.stack()

Survived               0          1
Pclass Sex
1      female  25.666667  34.939024
       male    44.581967  36.248000
2      female  36.000000  28.080882
       male    33.369048  16.022000
3      female  23.818182  19.329787
       male    27.255814  22.274211

In [46]:
"""Task 3: Create a pivot table with index='Embarked' and columns=['Pclass', 'Sex'] 
(values='Fare', aggfunc='median'). Then use .stack(level='Sex') to move the Sex level into the rows."""

pivot = pd.pivot_table(df, index='Embarked', columns=['Pclass', 'Sex'], values='Fare', aggfunc='median')
stacked = pivot.stack(level='Sex')
stacked

C:\Users\Faizan Toheed\AppData\Local\Temp\ipykernel_6488\3349950400.py:5: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked = pivot.stack(level='Sex')

Pclass                 1        2        3
Embarked Sex
C        female  83.1583  24.0000  14.4583
         male    61.6792  25.8604   7.2292
Q        female  90.0000  12.3500   7.7500
         male    90.0000  12.3500   7.7500
S        female  79.6500  23.0000  14.4500
         male    35.0000  13.0000   8.0500

In [48]:
"""Task 4 (Bonus): Using the pivot table from Task 3 (before stacking), use .unstack() on the 
row index (Embarked) to move it into the columns. What does the resulting DataFrame look like?"""

unstacked = stacked.unstack(level='Embarked')
unstacked

Pclass          1                     2                     3
Embarked        C     Q      S        C      Q     S        C     Q      S
Sex
female    83.1583  90.0  79.65  24.0000  12.35  23.0  14.4583  7.75  14.45
male      61.6792  90.0  35.00  25.8604  12.35  13.0   7.2292  7.75   8.05