In [23]:
#Day 7, Topic 1: .melt() – Unpivoting Wide Data to Long Format

import pandas as pd

In [24]:
#Basic .melt()
wide_df = pd.DataFrame({
    'Salesperson': ['Faizan', 'Faisal', 'Usman'],
    'Q1': [100, 150, 200],
    'Q2': [110, 160, 210],
    'Q3': [120, 170, 220],
    'Q4': [130, 180, 230]
})

wide_df

  Salesperson   Q1   Q2   Q3   Q4
0      Faizan  100  110  120  130
1      Faisal  150  160  170  180
2       Usman  200  210  220  230

In [25]:
long_df = wide_df.melt(
    id_vars=['Salesperson'],
    var_name='Quarter',
    value_name='Sales'
)

long_df

   Salesperson Quarter  Sales
0       Faizan      Q1    100
1       Faisal      Q1    150
2        Usman      Q1    200
3       Faizan      Q2    110
4       Faisal      Q2    160
5        Usman      Q2    210
6       Faizan      Q3    120
7       Faisal      Q3    170
8        Usman      Q3    220
9       Faizan      Q4    130
10      Faisal      Q4    180
11       Usman      Q4    230

In [26]:
# Melt only Q1 and Q2, ignore Q3 and Q4
melted_partial = wide_df.melt(id_vars=['Salesperson'], value_vars=['Q1', 'Q2'], var_name='Quarter', value_name='Sales')

melted_partial

  Salesperson Quarter  Sales
0      Faizan      Q1    100
1      Faisal      Q1    150
2       Usman      Q1    200
3      Faizan      Q2    110
4      Faisal      Q2    160
5       Usman      Q2    210

In [27]:
#Real‑World Use Case – Titanic
# Simulate a wide version: aggregate survival counts by class and sex

df = pd.read_csv('titanic.csv')

# Create a pivot table (wide format)
pivot = pd.pivot_table(df, values='PassengerId', index='Pclass', columns='Sex', aggfunc='count')
pivot.columns = ['Female', 'Male']  # simplify column names
pivot = pivot.reset_index()
pivot.columns.name = None
print("Wide pivot table:")
pivot

Wide pivot table:

   Pclass  Female  Male
0       1      94   122
1       2      76   108
2       3     144   347

In [28]:
long_pivot = pivot.melt(id_vars=['Pclass'], var_name='Sex', value_name='Count')
long_pivot

   Pclass     Sex  Count
0       1  Female     94
1       2  Female     76
2       3  Female    144
3       1    Male    122
4       2    Male    108
5       3    Male    347

In [29]:
#Practice: .melt() on Titanic Data
import pandas as pd

df = pd.read_csv('titanic.csv')

# Create a wide summary: average Fare per Pclass and Embarked
wide = pd.pivot_table(df, values='Fare', index='Pclass', columns='Embarked', aggfunc='mean', fill_value=0)
wide = wide.reset_index()
wide.columns.name = None
wide

   Pclass           C          Q          S
0       1  104.718529  90.000000  70.364862
1       2   25.358335  12.350000  20.327439
2       3   11.214083  11.183393  14.644083

In [30]:
"""Melt wide back to long format. Keep 'Pclass' as the identifier. 
The column headers ('C', 'Q', 'S') should become a new column named 'Port', 
and the fare values should be named 'Avg_Fare'. Display the result."""

long_pivot = wide.melt(id_vars=['Pclass'], value_vars=['C', 'Q', 'S'], var_name='Port', value_name='Avg_Fare')

long_pivot

   Pclass Port    Avg_Fare
0       1    C  104.718529
1       2    C   25.358335
2       3    C   11.214083
3       1    Q   90.000000
4       2    Q   12.350000
5       3    Q   11.183393
6       1    S   70.364862
7       2    S   20.327439
8       3    S   14.644083

In [31]:
#Day 7, Topic 2: .pivot() – Reshaping Long Data to Wide Format
import pandas as pd

In [32]:
#Basic .pivot() Syntax
long_df = pd.DataFrame({
    'Salesperson': ['Alice', 'Alice', 'Alice', 'Alice',
                    'Bob', 'Bob', 'Bob', 'Bob'],
    'Quarter': ['Q1', 'Q2', 'Q3', 'Q4',
                'Q1', 'Q2', 'Q3', 'Q4'],
    'Sales': [100, 110, 120, 130,
              150, 160, 170, 180]
})
print("Long format:")
long_df

Long format:

  Salesperson Quarter  Sales
0       Alice      Q1    100
1       Alice      Q2    110
2       Alice      Q3    120
3       Alice      Q4    130
4         Bob      Q1    150
5         Bob      Q2    160
6         Bob      Q3    170
7         Bob      Q4    180

In [33]:
wide_df = long_df.pivot(index='Salesperson', columns='Quarter', values='Sales')
wide_df

Quarter       Q1   Q2   Q3   Q4
Salesperson
Alice        100  110  120  130
Bob          150  160  170  180

In [34]:
#Handling Duplicate Entries
dup_df = pd.DataFrame({
    'Salesperson': ['Alice', 'Alice', 'Alice'],
    'Quarter': ['Q1', 'Q1', 'Q1'],
    'Sales': [100, 105, 110]
})

#dup_df.pivot(index='Salesperson', columns='Quarter', values='Sales')

In [35]:
#Real‑World Use Case – Titanic

df = pd.read_csv('titanic.csv')

# Create a long summary: average Fare per Pclass and Embarked
summary = df.groupby(['Pclass', 'Embarked'])['Fare'].mean().reset_index()
print("Long summary:")
summary

Long summary:

   Pclass Embarked        Fare
0       1        C  104.718529
1       1        Q   90.000000
2       1        S   70.364862
3       2        C   25.358335
4       2        Q   12.350000
5       2        S   20.327439
6       3        C   11.214083
7       3        Q   11.183393
8       3        S   14.644083

In [36]:
wide_summary = summary.pivot(index='Pclass', columns='Embarked', values='Fare')
wide_summary

Embarked           C          Q          S
Pclass
1         104.718529  90.000000  70.364862
2          25.358335  12.350000  20.327439
3          11.214083  11.183393  14.644083

In [37]:
#Practice: .pivot() on Titanic Data
import pandas as pd

df = pd.read_csv('titanic.csv')

# Long summary: count of passengers by Pclass, Sex, and Survived
long_counts = df.groupby(['Pclass', 'Sex', 'Survived'])['PassengerId'].count().reset_index()
long_counts.columns = ['Pclass', 'Sex', 'Survived', 'Count']
long_counts.head()

   Pclass     Sex  Survived  Count
0       1  female         0      3
1       1  female         1     91
2       1    male         0     77
3       1    male         1     45
4       2  female         0      6

In [40]:
"""Task:
Pivot long_counts so that:
Rows are Pclass
Columns are Sex
Values are Count
Display the result."""

# Pivot the summary data
# Rows become Pclass, Columns become Sex, and the Values are the Counts
wide_df = pd.pivot_table(
    long_counts, 
    index='Pclass', 
    columns='Sex', 
    values='Count', 
    aggfunc='sum'
)

# Display the result
wide_df

Sex     female  male
Pclass
1           94   122
2           76   108
3          144   347