In [5]:
#Day 8, Topic 5: Stacking and Unstacking MultiIndex DataFrames
import pandas as pd

df = pd.read_csv('titanic.csv')

# Create a pivot table with MultiIndex columns
pivot = pd.pivot_table(df, values='Fare', index='Pclass', columns=['Sex', 'Embarked'], aggfunc='mean')
print("Original pivot (MultiIndex columns):")
pivot

Original pivot (MultiIndex columns):

Sex           female                             male
Embarked           C          Q          S          C          Q          S
Pclass
1         115.640309  90.000000  99.026910  93.536707  90.000000  52.949947
2          25.268457  12.350000  21.912687  25.421250  12.350000  19.232474
3          14.694926  10.307833  18.670077   9.352237  11.924251  13.307149

In [6]:
stacked = pivot.stack(level='Sex')
stacked

Embarked                C          Q          S
Pclass Sex
1      female  115.640309  90.000000  99.026910
       male     93.536707  90.000000  52.949947
2      female   25.268457  12.350000  21.912687
       male     25.421250  12.350000  19.232474
3      female   14.694926  10.307833  18.670077
       male      9.352237  11.924251  13.307149

In [8]:
unstacked = stacked.unstack(level='Sex')

unstacked

Embarked           C                     Q                     S
Sex           female       male     female       male     female       male
Pclass
1         115.640309  93.536707  90.000000  90.000000  99.026910  52.949947
2          25.268457  25.421250  12.350000  12.350000  21.912687  19.232474
3          14.694926   9.352237  10.307833  11.924251  18.670077  13.307149

In [9]:
#Day 8, Topic 6: MultiIndex Aggregations (.groupby(level=))
import pandas as pd

In [10]:
#Basic .groupby(level=...)
multi = df.groupby(['Pclass', 'Sex', 'Embarked']).agg(
    Total_Fare=('Fare', 'sum'),
    Passengers=('PassengerId', 'count')
)

multi_sorted = multi.sort_index()

by_class = multi_sorted.groupby(level='Pclass').sum()
by_class

        Total_Fare  Passengers
Pclass
1       18017.4125         214
2        3801.8417         184
3        6714.6951         491

In [11]:
#Group by multiple index levels:
by_class_sex = multi_sorted.groupby(level=['Pclass', 'Sex']).sum()
by_class_sex

               Total_Fare  Passengers
Pclass Sex
1      female   9815.8250          92
       male     8201.5875         122
2      female   1669.7292          76
       male     2132.1125         108
3      female   2321.1086         144
       male     4393.5865         347

In [12]:
#Aggregating with Different Functions
stats = multi_sorted.groupby(level='Pclass').agg({'Total_Fare': 'mean', 'Passengers': 'sum'})
stats

         Total_Fare  Passengers
Pclass
1       3002.902083         214
2        633.640283         184
3       1119.115850         491

In [13]:
#Using Level Numbers
by_sex = multi_sorted.groupby(level=1).sum()
by_sex

        Total_Fare  Passengers
Sex
female  13806.6628         312
male    14727.2865         577

In [14]:
#Practice Activity: MultiIndex Aggregations

In [16]:
#Task 1: Group by the 'Embarked' level and compute the mean Total_Fare and sum of Passengers.


multi_sorted.groupby(level='Embarked').agg({'Total_Fare': 'mean', 'Passengers': 'sum'})

           Total_Fare  Passengers
Embarked
C         1678.716033         168
Q          170.375717          77
S         2906.566467         644

In [17]:
#Task 2: Group by both 'Pclass' and 'Sex' levels (using level names) and compute the sum of all columns.

multi_sorted.groupby(level=['Pclass', 'Sex']).sum()

               Total_Fare  Passengers
Pclass Sex
1      female   9815.8250          92
       male     8201.5875         122
2      female   1669.7292          76
       male     2132.1125         108
3      female   2321.1086         144
       male     4393.5865         347

In [20]:
#Task 3: Group by level 0 (Pclass) and compute the maximum Passengers count.

multi_sorted.groupby(level=0).agg({'Passengers': 'max'})

        Passengers
Pclass
1               79
2               97
3              265

In [21]:
#Task 4 (Bonus): Chain .groupby(level='Sex') and .agg() to compute the median Total_Fare and the mean Passengers per sex.

multi_sorted.groupby(level='Sex').agg({
    'Total_Fare': 'median',
    'Passengers': 'mean'
})

        Total_Fare  Passengers
Sex
female    340.1585   34.666667
male      465.0458   64.111111

In [25]:
#Day 8, Topic 7: Sorting MultiIndex
import pandas as pd
df = pd.read_csv('titanic.csv')

# Create MultiIndex DataFrame (unsorted – the groupby result is not sorted by default)
multi = df.groupby(['Pclass', 'Sex', 'Embarked']).agg(
    Total_Fare=('Fare', 'sum'),
    Passengers=('PassengerId', 'count')
)
print("Unsorted MultiIndex DataFrame:")
multi

Unsorted MultiIndex DataFrame:

                        Total_Fare  Passengers
Pclass Sex    Embarked
1      female C          4972.5333          43
              Q            90.0000           1
              S          4753.2917          48
       male   C          3928.5417          42
              Q            90.0000           1
              S          4183.0458          79
2      female C           176.8792           7
              Q            24.7000           2
              S          1468.1500          67
       male   C           254.2125          10
              Q            12.3500           1
              S          1865.5500          97
3      female C           337.9833          23
              Q           340.1585          33
              S          1642.9668          88
       male   C           402.1462          43
              Q           465.0458          39
              S          3526.3945         265

In [24]:
multi_sorted = multi.sort_index()
multi_sorted

                        Total_Fare  Passengers
Pclass Sex    Embarked
1      female C          4972.5333          43
              Q            90.0000           1
              S          4753.2917          48
       male   C          3928.5417          42
              Q            90.0000           1
              S          4183.0458          79
2      female C           176.8792           7
              Q            24.7000           2
              S          1468.1500          67
       male   C           254.2125          10
              Q            12.3500           1
              S          1865.5500          97
3      female C           337.9833          23
              Q           340.1585          33
              S          1642.9668          88
       male   C           402.1462          43
              Q           465.0458          39
              S          3526.3945         265

In [26]:
#Sorting by Specific Level
multi_sorted_sex = multi.sort_index(level='Sex')
multi_sorted_sex

                        Total_Fare  Passengers
Pclass Sex    Embarked
1      female C          4972.5333          43
              Q            90.0000           1
              S          4753.2917          48
2      female C           176.8792           7
              Q            24.7000           2
              S          1468.1500          67
3      female C           337.9833          23
              Q           340.1585          33
              S          1642.9668          88
1      male   C          3928.5417          42
              Q            90.0000           1
              S          4183.0458          79
2      male   C           254.2125          10
              Q            12.3500           1
              S          1865.5500          97
3      male   C           402.1462          43
              Q           465.0458          39
              S          3526.3945         265

In [27]:
#Descending Order
multi_desc = multi.sort_index(ascending=False)
multi_desc

                        Total_Fare  Passengers
Pclass Sex    Embarked
3      male   S          3526.3945         265
              Q           465.0458          39
              C           402.1462          43
       female S          1642.9668          88
              Q           340.1585          33
              C           337.9833          23
2      male   S          1865.5500          97
              Q            12.3500           1
              C           254.2125          10
       female S          1468.1500          67
              Q            24.7000           2
              C           176.8792           7
1      male   S          4183.0458          79
              Q            90.0000           1
              C          3928.5417          42
       female S          4753.2917          48
              Q            90.0000           1
              C          4972.5333          43

In [28]:
#Practice: Sorting MultiIndex

In [29]:
sort_multi = multi.sort_index()
sort_multi.loc[(1, 'male', 'C'):(2, 'female', 'S')]

                        Total_Fare  Passengers
Pclass Sex    Embarked
1      male   C          3928.5417          42
              Q            90.0000           1
              S          4183.0458          79
2      female C           176.8792           7
              Q            24.7000           2
              S          1468.1500          67

In [30]:
#Task 2: Sort multi by the 'Embarked' level only (level 2) in descending order. Display the result.

multi.sort_index(level=2, ascending=False)

                        Total_Fare  Passengers
Pclass Sex    Embarked
3      male   S          3526.3945         265
       female S          1642.9668          88
2      male   S          1865.5500          97
       female S          1468.1500          67
1      male   S          4183.0458          79
       female S          4753.2917          48
3      male   Q           465.0458          39
       female Q           340.1585          33
2      male   Q            12.3500           1
       female Q            24.7000           2
1      male   Q            90.0000           1
       female Q            90.0000           1
3      male   C           402.1462          43
       female C           337.9833          23
2      male   C           254.2125          10
       female C           176.8792           7
1      male   C          3928.5417          42
       female C          4972.5333          43

In [31]:
"""Task 3: Sort multi by the first two levels ascending and the third level descending. 
Use ascending=[True, True, False]. Display the first 10 rows."""

multi.sort_index(ascending=[True, True, False])

                        Total_Fare  Passengers
Pclass Sex    Embarked
1      female S          4753.2917          48
              Q            90.0000           1
              C          4972.5333          43
       male   S          4183.0458          79
              Q            90.0000           1
              C          3928.5417          42
2      female S          1468.1500          67
              Q            24.7000           2
              C           176.8792           7
       male   S          1865.5500          97
              Q            12.3500           1
              C           254.2125          10
3      female S          1642.9668          88
              Q           340.1585          33
              C           337.9833          23
       male   S          3526.3945         265
              Q           465.0458          39
              C           402.1462          43