In [17]:
#Day 8, Topic 3: Selecting from MultiIndex
import pandas as pd
df = pd.read_csv('titanic.csv')

In [18]:
# Create a MultiIndex DataFrame
multi = df.groupby(['Pclass', 'Sex', 'Embarked']).agg(
    Total_Fare=('Fare', 'sum'),
    Passengers=('PassengerId', 'count')
)
multi.head(10)

                        Total_Fare  Passengers
Pclass Sex    Embarked
1      female C          4972.5333          43
              Q            90.0000           1
              S          4753.2917          48
       male   C          3928.5417          42
              Q            90.0000           1
              S          4183.0458          79
2      female C           176.8792           7
              Q            24.7000           2
              S          1468.1500          67
       male   C           254.2125          10

In [19]:
#Selecting by First Level
multi.loc[1]

                 Total_Fare  Passengers
Sex    Embarked
female C          4972.5333          43
       Q            90.0000           1
       S          4753.2917          48
male   C          3928.5417          42
       Q            90.0000           1
       S          4183.0458          79

In [20]:
#Selecting by a Tuple
multi.loc[(1, 'male')]

          Total_Fare  Passengers
Embarked
C          3928.5417          42
Q            90.0000           1
S          4183.0458          79

In [21]:
#Slicing on MultiIndex
multi_sorted = multi.sort_index()

multi_sorted.loc[(1, 'male'):(2, 'female')]

                        Total_Fare  Passengers
Pclass Sex    Embarked
1      male   C          3928.5417          42
              Q            90.0000           1
              S          4183.0458          79
2      female C           176.8792           7
              Q            24.7000           2
              S          1468.1500          67

In [22]:
#Using slice(None) and IndexSlice
idx = pd.IndexSlice

result = multi_sorted.loc[idx[1, :, 'C'], :]
result

                        Total_Fare  Passengers
Pclass Sex    Embarked
1      female C          4972.5333          43
       male   C          3928.5417          42

In [23]:
#Selecting Columns with MultiIndex Rows
multi.loc[1, 'Total_Fare']

Sex     Embarked
female  C           4972.5333
        Q             90.0000
        S           4753.2917
male    C           3928.5417
        Q             90.0000
        S           4183.0458
Name: Total_Fare, dtype: float64

In [24]:
#Practice Activity: Selecting from MultiIndex
import pandas as pd

df = pd.read_csv('titanic.csv')
# Create a MultiIndex DataFrame
multi = df.groupby(['Pclass', 'Sex', 'Embarked']).agg(
    Total_Fare=('Fare', 'sum'),
    Passengers=('PassengerId', 'count')
)
multi.head(10)

                        Total_Fare  Passengers
Pclass Sex    Embarked
1      female C          4972.5333          43
              Q            90.0000           1
              S          4753.2917          48
       male   C          3928.5417          42
              Q            90.0000           1
              S          4183.0458          79
2      female C           176.8792           7
              Q            24.7000           2
              S          1468.1500          67
       male   C           254.2125          10

In [25]:
#Slicing on MultiIndex
multi_sorted = multi.sort_index()
multi_sorted.head(10)

                        Total_Fare  Passengers
Pclass Sex    Embarked
1      female C          4972.5333          43
              Q            90.0000           1
              S          4753.2917          48
       male   C          3928.5417          42
              Q            90.0000           1
              S          4183.0458          79
2      female C           176.8792           7
              Q            24.7000           2
              S          1468.1500          67
       male   C           254.2125          10

In [26]:
#Task 1: Select all rows where Pclass=2 and Sex='female'. Display the result.

multi_sorted.loc[(2, 'female')]

          Total_Fare  Passengers
Embarked
C           176.8792           7
Q            24.7000           2
S          1468.1500          67

In [27]:
#Task 2: Using the sorted MultiIndex (multi_sorted), slice from (1, 'male', 'C') to (2, 'female', 'S') inclusive. Show the resulting rows.

range_slice = multi_sorted.loc[(1, 'male', 'C') : (2, 'female', 'S')]
range_slice

                        Total_Fare  Passengers
Pclass Sex    Embarked
1      male   C          3928.5417          42
              Q            90.0000           1
              S          4183.0458          79
2      female C           176.8792           7
              Q            24.7000           2
              S          1468.1500          67

In [28]:
#Task 3: Use IndexSlice to select all rows where Pclass=3 and Embarked='S', for any sex. Display the result.

idx = pd.IndexSlice

multi_sorted.loc[idx[3, :, 'S'], :]

                        Total_Fare  Passengers
Pclass Sex    Embarked
3      female S          1642.9668          88
       male   S          3526.3945         265

In [29]:
#Task 4 (Bonus): Using .loc[] with a tuple, select only the 'Passengers' column for (2, 'male', 'C'). Print the value.

multi_sorted.loc[(2, 'male', 'C'), 'Passengers']

np.int64(10)

In [31]:
#Day 8, Topic 4: Cross‑Section with .xs()
import pandas as pd
df = pd.read_csv('titanic.csv')

multi = df.groupby(['Pclass', 'Sex', 'Embarked']).agg(
    Total_Fare=('Fare', 'sum'),
    Passengers=('PassengerId', 'count')
)
multi_sorted = multi.sort_index()
multi_sorted.head(6)

                        Total_Fare  Passengers
Pclass Sex    Embarked
1      female C          4972.5333          43
              Q            90.0000           1
              S          4753.2917          48
       male   C          3928.5417          42
              Q            90.0000           1
              S          4183.0458          79

In [32]:
#select all rows where Sex='male', regardless of Pclass or Embarked.

males = multi_sorted.xs('male', level='Sex')
males

                 Total_Fare  Passengers
Pclass Embarked
1      C          3928.5417          42
       Q            90.0000           1
       S          4183.0458          79
2      C           254.2125          10
       Q            12.3500           1
       S          1865.5500          97
3      C           402.1462          43
       Q           465.0458          39
       S          3526.3945         265

In [33]:
#use drop_level=False
males_with_level = multi_sorted.xs('male', level='Sex', drop_level=False)
males_with_level

                      Total_Fare  Passengers
Pclass Sex  Embarked
1      male C          3928.5417          42
            Q            90.0000           1
            S          4183.0458          79
2      male C           254.2125          10
            Q            12.3500           1
            S          1865.5500          97
3      male C           402.1462          43
            Q           465.0458          39
            S          3526.3945         265

In [34]:
#Selecting by Level Number Instead of Name
embarked_C = multi_sorted.xs('C', level=2)
embarked_C.head()

               Total_Fare  Passengers
Pclass Sex
1      female   4972.5333          43
       male     3928.5417          42
2      female    176.8792           7
       male      254.2125          10
3      female    337.9833          23

In [38]:
#Using .xs() with axis=1 (Columns)
cols = pd.MultiIndex.from_product([['Fare', 'Age'], ['mean', 'median']])
demo = pd.DataFrame([[1, 2, 3, 4], [5, 6, 7, 8]], columns=cols)

demo.xs('mean', level=1, axis=1)

   Fare  Age
0     1    3
1     5    7

In [39]:
#Practice Activity: .xs() on Titanic MultiIndex
import pandas as pd
df = pd.read_csv('titanic.csv')

multi = df.groupby(['Pclass', 'Sex', 'Embarked']).agg(
    Total_Fare=('Fare', 'sum'),
    Passengers=('PassengerId', 'count')
)
multi_sorted = multi.sort_index()
multi_sorted.head(6)

                        Total_Fare  Passengers
Pclass Sex    Embarked
1      female C          4972.5333          43
              Q            90.0000           1
              S          4753.2917          48
       male   C          3928.5417          42
              Q            90.0000           1
              S          4183.0458          79

In [41]:
#Task 1: Use .xs() to select all rows where Embarked='S'. Display the first 3 rows of the result.

multi_sorted.xs('S', level='Embarked')

               Total_Fare  Passengers
Pclass Sex
1      female   4753.2917          48
       male     4183.0458          79
2      female   1468.1500          67
       male     1865.5500          97
3      female   1642.9668          88
       male     3526.3945         265

In [42]:
#Task 2: Select all rows for Pclass=2 using .xs(). Display the result.

multi_sorted.xs(2)

                 Total_Fare  Passengers
Sex    Embarked
female C           176.8792           7
       Q            24.7000           2
       S          1468.1500          67
male   C           254.2125          10
       Q            12.3500           1
       S          1865.5500          97

In [ ]:
"""Task 3: Using .xs() with drop_level=False, select Sex='female' while keeping the Sex level in 
the resulting DataFrame. Verify that the Sex column still appears in the index by printing the first 3 rows."""

multi_sorted.xs('female', level='Sex', drop_level=False).head(3)

                        Total_Fare  Passengers
Pclass Sex    Embarked
1      female C          4972.5333          43
              Q            90.0000           1
              S          4753.2917          48
2      female C           176.8792           7
              Q            24.7000           2

In [45]:
#Task 4 (Bonus): Use .xs() on the columns of the following DataFrame:
cols = pd.MultiIndex.from_product([['Fare', 'Age'], ['mean', 'std']])
demo = pd.DataFrame([[30.5, 12.0, 22.0, 8.5],
                      [70.2, 15.4, 28.0, 6.2]],
                    index=['Male', 'Female'],
                    columns=cols)
demo

        Fare         Age
        mean   std  mean  std
Male    30.5  12.0  22.0  8.5
Female  70.2  15.4  28.0  6.2

In [46]:
#Extract only the 'std' statistics using .xs() with level=1 and axis=1. Display the result.

demo.xs('std', level=1, axis=1)

        Fare  Age
Male    12.0  8.5
Female  15.4  6.2