In [3]:
#Day 8, Topic 1: Setting and Resetting Index
import pandas as pd

In [4]:
#.set_index() – Turn a Column into the Row Index
df = pd.read_csv('titanic.csv')
df_indexed = df.set_index('PassengerId')
df_indexed.head(2)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [5]:
#.reset_index() – Turn the Index Back into a Column
df_reset = df_indexed.reset_index()
df_reset.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [6]:
#Practice Activity: Setting and Resetting Index
import pandas as pd
df = pd.read_csv('titanic.csv')

In [7]:
#Task 1: Set the 'Name' column as the index of df. Display the first 3 rows. (Names are unique in this dataset, 
# so it works as a unique index.)

df_name = df.set_index('Name')
df_name.head(3)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [9]:
"""Task 2: Use .reset_index() to revert to the default integer index. Then set both 'Pclass' and 'Sex' 
as a hierarchical index using .set_index() with a list. Display the first 5 rows."""

df_reset = df_name.reset_index()
df_indexed = df.set_index(['Pclass', 'Sex'])
df_indexed.head(5)

,,PassengerId,Survived,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,Sex,,,,,,,,,,
3,male,1,0,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S
1,female,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C
3,female,3,1,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,female,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S
3,male,5,0,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S

In [11]:
#Task 3: From the result of Task 2, reset the index without dropping the newly created 
# columns (so Pclass and Sex should reappear as columns). Verify they are present.

df_reset = df_indexed.reset_index()
df_reset.columns.tolist()

['Pclass',
 'Sex',
 'PassengerId',
 'Survived',
 'Name',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [13]:
"""Task 4 (Bonus): On the original df, set 'PassengerId' as the index, 
but keep the 'PassengerId' column as well (use drop=False). Then select the row 
for PassengerId=10 using .loc[]. Print the passenger's name."""

df_id = df.set_index('PassengerId', drop=False)
df_id.loc[10, 'Name']

'Nasser, Mrs. Nicholas (Adele Achem)'

In [14]:
#Day 8, Topic 2: Creating MultiIndex
import pandas as pd

In [15]:
#Creating a MultiIndex from Tuples or Arrays
tuples = [('North', 2022), ('North', 2023), ('South', 2022), ('South', 2023)]
multi_index = pd.MultiIndex.from_tuples(tuples, name=['Region', 'Year'])

data = [100, 150, 200, 250]
df_tuples = pd.DataFrame({'Sales': data}, index=multi_index)
df_tuples

             Sales
Region Year
North  2022    100
       2023    150
South  2022    200
       2023    250

In [17]:
regions = ['North', 'North', 'South', 'South']
years = [2022, 2023, 2022, 2023]
multi_index2 = pd.MultiIndex.from_arrays([regions, years], names=['Region', 'Year'])
df_arrays = pd.DataFrame({'Sales': data}, index=multi_index2)
df_arrays

             Sales
Region Year
North  2022    100
       2023    150
South  2022    200
       2023    250

In [18]:
#Creating a MultiIndex from a Product (Cartesian Product)
regions = ['North', 'South']
years = [2022, 2023]
multi_product = pd.MultiIndex.from_product([regions, years], names=['Region', 'Year'])
df_product = pd.DataFrame(index=multi_product)
df_product['Sales'] = [100, 150, 170, 200]
df_product

             Sales
Region Year
North  2022    100
       2023    150
South  2022    170
       2023    200

In [21]:
#Creating a MultiIndex with .set_index() on Multiple Columns
df = pd.read_csv('titanic.csv')
df_multi = df.set_index(['Pclass', 'Sex'])
df_multi.head()

,,PassengerId,Survived,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,Sex,,,,,,,,,,
3,male,1,0,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S
1,female,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C
3,female,3,1,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,female,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S
3,male,5,0,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S

In [22]:
#MultiIndex from groupby() Results
avg_fare = df.groupby(['Pclass', 'Sex'])['Fare'].mean()
avg_fare

Pclass  Sex
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64

In [23]:
#Adding Levels to an Existing Index
df_id = df.set_index('PassengerId')
df_multi2 = df_id.set_index('Pclass', append=True)
df_multi2.head()

,,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,Pclass,,,,,,,,,,
1,3,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,3,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [24]:
#Practice Activity: Creating MultiIndex
import pandas as pd
df = pd.read_csv('titanic.csv')

In [32]:
"""Task 1: Create a MultiIndex from tuples: (1, 'male'), (1, 'female'), (2, 'male'), (2, 'female'), (3, 'male'), 
(3, 'female'). Assign it to a DataFrame with a column 'Count' 
containing the number of passengers in each group 
(you'll need to compute those counts first). Display the result."""

tuples = [(1, 'male'), (1, 'female'), (2, 'male'), (2, 'female'), (3, 'male'), (3, 'female')]
multi_index = pd.MultiIndex.from_tuples(tuples, names=['Pclass', 'Sex'])

counts = df.groupby(['Pclass', 'Sex']).size()

multi_df = pd.DataFrame(counts, index=multi_index, columns=['Count'])

multi_df

               Count
Pclass Sex
1      male      122
       female     94
2      male      108
       female     76
3      male      347
       female    144

In [26]:
"""Task 2: Use pd.MultiIndex.from_product() to create an index of all combinations 
of ['C', 'Q', 'S'] (Embarked) and [0, 1] (Survived). Create an empty DataFrame 
with this index and then fill a column 'Total_Fare' with the sum of Fare for 
each combination (compute the required values). Display the filled DataFrame."""

embarked = ['C', 'Q', 'S']
survived = [0, 1]
multi = pd.MultiIndex.from_product([embarked, survived], names=['Embarked', 'Survived'])

data = pd.DataFrame(index=multi)
data['TotalFare'] = df.groupby(['Embarked', 'Survived'])['Fare'].sum()

data

                   TotalFare
Embarked Survived
C        0         2658.2501
         1         7414.0461
Q        0          626.7875
         1          395.4668
S        0         8857.6823
         1         8581.7165

In [30]:
"""Task 3: Set a MultiIndex on the original df using the columns 'Embarked' and 'Pclass'. 
Then use .reset_index(level='Embarked') to move only the 'Embarked' level 
back to columns while keeping Pclass as the index."""

df_set = df.set_index(['Embarked', 'Pclass'])
df_reset = df_set.reset_index(level='Embarked')
df_reset.head()

,Embarked,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
Pclass,,,,,,,,,,,
3,S,1,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN
1,C,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85
3,S,3,1,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN
1,S,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123
3,S,5,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN

In [33]:
"""Task 4 (Bonus): Using the MultiIndex from Task 1, use .loc[] to select the row for Pclass=1
and Sex='female'. Print the count."""


tuples = [(1, 'male'), (1, 'female'), (2, 'male'), (2, 'female'), (3, 'male'), (3, 'female')]
multi_index = pd.MultiIndex.from_tuples(tuples, names=['Pclass', 'Sex'])

counts = df.groupby(['Pclass', 'Sex']).size()

multi_df = pd.DataFrame(counts, index=multi_index, columns=['Count'])

multi_df.loc[1, 'female']

Count    94
Name: (1, female), dtype: int64