In [4]:
#Day 2, Topic 1: Label-Based Selection with .loc

import pandas as pd
df = pd.read_csv('titanic.csv')

In [5]:
#Selecting Rows by Index Label

row_0 = df.loc[0]
print(row_0)

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [6]:
#Select multiple rows by passing a list of labels:
row_0_2_5 = df.loc[[0, 2, 5]]
print(row_0_2_5[['Name', 'Age']])

                      Name   Age
0  Braund, Mr. Owen Harris  22.0
2   Heikkinen, Miss. Laina  26.0
5         Moran, Mr. James   NaN

In [9]:
#Selecting Rows and Specific Columns
name_0 = df.loc[0, 'Name']
print(name_0)

data_0_2_5 = df.loc[[0, 2, 5], ['Name', 'Age']]
print(data_0_2_5)

Braund, Mr. Owen Harris
                      Name   Age
0  Braund, Mr. Owen Harris  22.0
2   Heikkinen, Miss. Laina  26.0
5         Moran, Mr. James   NaN

In [10]:
#Slicing with Labels (Inclusive!)
row_0_to_5 = df.loc[0:5, ['Name', 'Age']]
print(row_0_to_5)

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0
5                                   Moran, Mr. James   NaN

In [12]:
#Slice columns by name:
df.loc[:, 'Name':'Age'].head()

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

In [19]:
#Selecting All Rows or All Columns

col_fare = df.loc[:, 'Fare']

row_data = df.loc[0:10, :]

In [22]:
#Boolean Indexing with .loc
mask = df['Sex'] == 'female'

women = df.loc[mask, ['Name', 'Age', 'Fare']].head()
print(women)

                                                Name   Age     Fare
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                             Heikkinen, Miss. Laina  26.0   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0  11.1333
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0  30.0708

In [23]:
#Combine multiple conditions:

condition = (df['Sex'] == 'female') & (df['Pclass'] == 1) & (df['Age'] > 30)
first_class_older_women = df.loc[condition, ['Name', 'Age', 'Fare']].head()
print(first_class_older_women)

                                                 Name   Age     Fare
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
11                           Bonnell, Miss. Elizabeth  58.0  26.5500
52           Harper, Mrs. Henry Sleeper (Myna Haxtun)  49.0  76.7292
61                                Icard, Miss. Amelie  38.0  80.0000

In [26]:
#Setting a Meaningful Index

df_indexed = df.set_index('PassengerId')

passenger_5 = df_indexed.loc[5]

print(passenger_5[['Name', 'Pclass']])

Name      Allen, Mr. William Henry
Pclass                           3
Name: 5, dtype: object

Practice Activity: .loc

In [27]:
import pandas as pd

df = pd.read_csv('titanic.csv')

In [29]:
#Task 1: Select the row with index label 10. Print the passenger's name and age.
row_10 = df.loc[10, ['Name', 'Age']]
print(row_10)

Name    Sandstrom, Miss. Marguerite Rut
Age                                 4.0
Name: 10, dtype: object

In [30]:
#Task 2: Select rows with labels 5, 20, and 50. Display only the Name and Fare columns.
data = df.loc[[5, 20, 50], ['Name', 'Fare']]
print(data)

                          Name     Fare
5             Moran, Mr. James   8.4583
20        Fynney, Mr. Joseph J  26.0000
50  Panula, Master. Juha Niilo  39.6875

In [31]:
#Task 3: Using label slicing, select rows from label 0 to label 3 (inclusive) and 
# columns from 'Name' to 'Age' (inclusive). Print the result.

data_1 = df.loc[0:3, 'Name':'Age']
print(data_1)

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0

In [33]:
#Task 4: Create a Boolean mask for male passengers who survived. Use .loc to display their Name, Age, and Pclass.

mask = df['Sex'] == 'male'

data_2 = df.loc[mask, ['Name', 'Age', 'Pclass']].head()
print(data_2)

                             Name   Age  Pclass
0         Braund, Mr. Owen Harris  22.0       3
4        Allen, Mr. William Henry  35.0       3
5                Moran, Mr. James   NaN       3
6         McCarthy, Mr. Timothy J  54.0       1
7  Palsson, Master. Gosta Leonard   2.0       3

In [34]:
#Task 5: Set PassengerId as the index. Then use .loc to select the passenger with ID 100. Print their name and fare.

df_indexed = df.set_index('PassengerId')
passenger_100 = df_indexed.loc[100]
print(f"Name: {passenger_100['Name']}, Fare: {passenger_100['Fare']}")

Name: Kantor, Mr. Sinai, Fare: 26.0

In [35]:
"""Task 6 (Bonus): Find all passengers whose name contains 'Mrs'. Use .loc with a 
string condition (.str.contains()) to select their Name and Age.
"""

mrs_passenger = df.loc[df['Name'].str.contains('Mrs', na=False), ['Name', 'Age']]
print(mrs_passenger)

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0
15                    Hewlett, Mrs. (Mary D Kingcome)   55.0
..                                                 ...   ...
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0
885               Rice, Mrs. William (Margaret Norton)  39.0

[129 rows x 2 columns]

Day 2, Topic 2: Position-Based Selection with .iloc

In [37]:
import pandas as pd
 
df = pd.read_csv('titanic.csv')

In [38]:
#Selecting Rows by Position
first_row = df.iloc[0]
print(first_row[['Name', 'Age']])

Name    Braund, Mr. Owen Harris
Age                        22.0
Name: 0, dtype: object

In [39]:
#Multiple rows by list:
row_0_2_5 = df.iloc[[0, 2, 5]]
print(row_0_2_5[['Name', 'Age']])

                      Name   Age
0  Braund, Mr. Owen Harris  22.0
2   Heikkinen, Miss. Laina  26.0
5         Moran, Mr. James   NaN

In [40]:
#Slicing rows (exclusive end):
first_five = df.iloc[0:5]
print(first_five[['Name', 'Age']])

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [42]:
#Selecting Rows and Columns Simultaneously
name_0 = df.iloc[0, 3]
print(name_0)

subset = df.iloc[[0, 2, 5], [3, 5]]
print(subset)

Braund, Mr. Owen Harris
                      Name   Age
0  Braund, Mr. Owen Harris  22.0
2   Heikkinen, Miss. Laina  26.0
5         Moran, Mr. James   NaN

In [43]:
#Slicing Rows and Columns
df.iloc[0:5, 3:6]

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

In [48]:
#Selecting All Rows or All Columns
df.iloc[:, 0:3]

df.iloc[0:10, :]

df.iloc[:, :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [51]:
#Negative Indexing
df.iloc[-1]

df.iloc[-5:, 0:3]

df.iloc[:-1, -1]

0      S
1      C
2      S
3      S
4      S
      ..
885    Q
886    S
887    S
888    S
889    C
Name: Embarked, Length: 890, dtype: object

In [53]:
#Finding Column Positions
name_pos = df.columns.get_loc('Name')
print(name_pos)

df.iloc[0, name_pos]

3

'Braund, Mr. Owen Harris'

In [54]:
#Practice Activity: .iloc
import pandas as pd
df = pd.read_csv('titanic.csv')

In [55]:
#Task 1: Select the first row using .iloc. Print the passenger's name and class (Pclass).

passenger_info = df.iloc[0]
print(passenger_info[['Name', 'Pclass']])

Name      Braund, Mr. Owen Harris
Pclass                          3
Name: 0, dtype: object

In [56]:
#Task 2: Select the last 3 rows. Display only the Name and Survived columns

df.iloc[-3:, [1, 3]]

     Survived                                      Name
888         0  Johnston, Miss. Catherine Helen "Carrie"
889         1                     Behr, Mr. Karl Howell
890         0                       Dooley, Mr. Patrick

In [59]:
"""Task 3: Using slicing, select rows at positions 10 through 14 (inclusive of 10, exclusive of 15) 
and columns at positions 2 through 5 (inclusive of 2, exclusive of 6). 
What columns are these? Print the result."""
df.iloc[10:15, 2:6]

    Pclass                                  Name     Sex   Age
10       3       Sandstrom, Miss. Marguerite Rut  female   4.0
11       1              Bonnell, Miss. Elizabeth  female  58.0
12       3        Saundercock, Mr. William Henry    male  20.0
13       3           Andersson, Mr. Anders Johan    male  39.0
14       3  Vestrom, Miss. Hulda Amanda Adolfina  female  14.0

In [60]:
#Task 4: Select the 5th row (position 4) and the last column (position -1). Print the value.
df.iloc[4, -1]

'S'

In [61]:
"""Task 5: Set PassengerId as the index. Then use .iloc to select the 100th row (position 99). 
Print the passenger's name.
"""
df_indexed = df.set_index('PassengerId')
passenger_100 = df_indexed.iloc[99]
print(passenger_100['Name'])

Kantor, Mr. Sinai

In [62]:
"""Task 6 (Bonus): Use .iloc to select every 10th row (positions 0, 10, 20, ...) and the columns Name, Age, Fare."""

df.iloc[::10, [3, 5, 9]]

                                               Name   Age     Fare
0                           Braund, Mr. Owen Harris  22.0   7.2500
10                  Sandstrom, Miss. Marguerite Rut   4.0  16.7000
20                             Fynney, Mr. Joseph J  35.0  26.0000
30                         Uruchurtu, Don. Manuel E  40.0  27.7208
40   Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  40.0   9.4750
..                                              ...   ...      ...
850         Andersson, Master. Sigvard Harald Elias   4.0  31.2750
860                         Hansen, Mr. Claus Peter  41.0  14.1083
870                               Balkic, Mr. Cerin  26.0   7.8958
880    Shelley, Mrs. William (Imanita Parrish Hall)  25.0  26.0000
890                             Dooley, Mr. Patrick  32.0   7.7500

[90 rows x 3 columns]