Day 2, Topic 3: Direct Column Access (Bracket Notation)

In [15]:
import pandas as pd
df = pd.read_csv('titanic.csv')

In [16]:
#Single Bracket – df['column']
age = df['Age']
print(type(age))
print(age.head())

<class 'pandas.core.series.Series'>
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

In [17]:
#Dot Notation – df.column
name = df.Name
print(name.head())

fare = df.Fare
print(fare.mean())

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object
32.204207968574636

In [18]:
#Double Bracket – df[['col1', 'col2']]
subset = df[['Name', 'Age', 'Fare']]
print(type(subset))
print(subset.head())

<class 'pandas.core.frame.DataFrame'>
                                                Name   Age     Fare
0                            Braund, Mr. Owen Harris  22.0   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                             Heikkinen, Miss. Laina  26.0   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                           Allen, Mr. William Henry  35.0   8.0500

In [19]:
# Create a new column
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

# Update an existing column
df['Fare'] = df['Fare'] * 1.1   # 10% increase

# Delete a column (using del)
del df['Ticket']
# Or using drop (safer, returns new DataFrame)
df = df.drop('Cabin', axis=1)

In [21]:
#Dynamic Column Selection

selected = [col for col in df.columns if 'Name' in col or 'Age' in col]
df[selected].head()

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [23]:
#Practice Activity: Column Access Mastery (Titanic)

import pandas as pd
df = pd.read_csv('titanic.csv')

In [24]:
#Task 1: Using bracket notation, select the Fare column and compute its mean.
df['Fare'].mean()

np.float64(32.204207968574636)

In [25]:
#Task 2: Using dot notation, select the Sex column and print the value counts.
df.Sex.value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [26]:
"""Task 3: Using double bracket notation, select the columns Name, Age, and Survived. Display the first 5 rows."""
df[['Name', 'Age', 'Survived']].head()

                                                Name   Age  Survived
0                            Braund, Mr. Owen Harris  22.0         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2                             Heikkinen, Miss. Laina  26.0         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
4                           Allen, Mr. William Henry  35.0         0

In [28]:
#Task 4: Try to access the Survived column with dot notation (df.Survived). Does it work? Why?
df.Survived.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [29]:
#Task 5: Create a new column AgeInMonths = Age * 12 using bracket assignment.
df['AgeInMonths'] = df['Age'] * 12

In [37]:
"""Task 6: Try to select a column called Passenger Class using dot notation. 
(Rename Pclass to Passenger Class first.) What happens? Then use bracket notation correctly.
"""
df.rename(columns={'Pclass': 'Passenger Class'}, inplace=True)

In [36]:
"""Task 7 (Bonus): Dynamically select all columns whose names start with the letter 'S'. Display the first 3 rows."""

selected = [col for col in df.columns if col.startswith('S')]
df[selected].head(3)

   Survived     Sex  SibSp
0         0    male      1
1         1  female      1
2         1  female      0

In [39]:
#Day 2, Topic 4: Boolean Indexing (Masking)

import pandas as pd

df =pd.read_csv('titanic.csv')

In [44]:
#Part 1: Creating a Boolean Mask
mask = df['Age'] > 30
mask.head(10)

0    False
1     True
2    False
3     True
4     True
5    False
6     True
7    False
8    False
9    False
Name: Age, dtype: bool

In [45]:
#Applying the Mask to Filter Rows
older_passengers = df[mask]
older_passengers[['Name', 'Age']].head()

                                                 Name   Age
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                            Allen, Mr. William Henry  35.0
6                             McCarthy, Mr. Timothy J  54.0
11                           Bonnell, Miss. Elizabeth  58.0

In [46]:
#Combining Multiple Conditions
# Female passengers in first class
mask = (df['Sex'] == 'female') & (df['Pclass'] == 1)
first_class_women = df[mask]
first_class_women[['Name', 'Sex', 'Pclass']].head()

                                                 Name     Sex  Pclass
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female       1
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female       1
11                           Bonnell, Miss. Elizabeth  female       1
31     Spencer, Mrs. William Augustus (Marie Eugenie)  female       1
52           Harper, Mrs. Henry Sleeper (Myna Haxtun)  female       1

In [47]:
# Passengers from first or second class
mask = (df['Pclass'] == 1) | (df['Pclass'] == 2)
first_or_second_class = df[mask]
first_or_second_class[['Name', 'Sex', 'Pclass']].head()

                                                 Name     Sex  Pclass
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female       1
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female       1
6                             McCarthy, Mr. Timothy J    male       1
9                 Nasser, Mrs. Nicholas (Adele Achem)  female       2
11                           Bonnell, Miss. Elizabeth  female       1

In [49]:
#NOT condition: 
# Passengers not from Southampton

mask = ~(df['Embarked'] == 'S')

not_southHampton = df[mask]

In [51]:
#Filtering with .loc and Boolean Masks

# Names and fares of female survivors

female_survivors = df.loc[(df['Sex'] == 'female') & (df['Survived'] == 1), ['Name', 'Fare']]
female_survivors

                                                  Name     Fare
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  71.2833
2                               Heikkinen, Miss. Laina   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  53.1000
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  11.1333
9                  Nasser, Mrs. Nicholas (Adele Achem)  30.0708
..                                                 ...      ...
874              Abelson, Mrs. Samuel (Hannah Wizosky)  24.0000
875                   Najib, Miss. Adele Kiamie "Jane"   7.2250
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  83.1583
880       Shelley, Mrs. William (Imanita Parrish Hall)  26.0000
887                       Graham, Miss. Margaret Edith  30.0000

[233 rows x 2 columns]

In [53]:
#Handling NaN in Boolean Masks
df[df['Age'].isna()].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q

In [55]:
#Boolean Masks with String Methods
mrs_mask = df['Name'].str.contains('Mrs')
df[mrs_mask].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S

In [56]:
#Practice Activity: Boolean Indexing 
import pandas as pd

df = pd.read_csv('titanic.csv')

In [71]:
#Task 1: Filter the DataFrame to show only passengers who survived. How many survivors are there?


(df['Survived'] == 1).sum()

np.int64(342)

In [72]:
#Task 2: Filter to show only female passengers who survived. How many are there?
mask = (df['Sex'] == 'female') & (df['Survived'] == 1)
mask.sum()

np.int64(233)

In [63]:
"""Task 3: Filter to show passengers who are either in first class or paid a fare greater than 100. 
Display the Name, Pclass, and Fare columns."""

mask = (df['Pclass'] == 1) | (df['Fare'] > 100) 
elite_persons = df[mask]
elite_persons[['Name', 'Pclass', 'Fare']].head(10)

                                                 Name  Pclass      Fare
1   Cumings, Mrs. John Bradley (Florence Briggs Th...       1   71.2833
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   53.1000
6                             McCarthy, Mr. Timothy J       1   51.8625
11                           Bonnell, Miss. Elizabeth       1   26.5500
23                       Sloper, Mr. William Thompson       1   35.5000
27                     Fortune, Mr. Charles Alexander       1  263.0000
30                           Uruchurtu, Don. Manuel E       1   27.7208
31     Spencer, Mrs. William Augustus (Marie Eugenie)       1  146.5208
34                            Meyer, Mr. Edgar Joseph       1   82.1708
35                     Holverson, Mr. Alexander Oskar       1   52.0000

In [65]:
"""Task 4: Filter to show passengers who embarked at Southampton ('S') AND are older than 50. 
Display their Name, Age, and Embarked.
"""
mask = (df['Embarked'] == 'S') & (df['Age'] > 50)
older_southampton = df[mask]
older_southampton[['Name', 'Age', 'Embarked']].head()

                                Name   Age Embarked
6            McCarthy, Mr. Timothy J  54.0        S
11          Bonnell, Miss. Elizabeth  58.0        S
15  Hewlett, Mrs. (Mary D Kingcome)   55.0        S
33             Wheadon, Mr. Edward H  66.0        S
94                 Coxon, Mr. Daniel  59.0        S

In [68]:
"""Task 5: Use .loc with a Boolean mask to select the Name and Age of all passengers who have a missing Cabin value. 
(Hint: df['Cabin'].isna())"""

missing_cabin = df.loc[df['Cabin'].isna(), ['Name', 'Age']]
missing_cabin.head()

                             Name   Age
0         Braund, Mr. Owen Harris  22.0
2          Heikkinen, Miss. Laina  26.0
4        Allen, Mr. William Henry  35.0
5                Moran, Mr. James   NaN
7  Palsson, Master. Gosta Leonard   2.0

In [69]:
"""Task 6 (Bonus): Find all passengers whose name contains 'Master' (a title often given to young boys). 
Display their Name and Age."""

master_mask = df['Name'].str.contains('Master')
master_passenger = df[master_mask]
master_passenger[['Name', 'Age']].head()

                                  Name   Age
7       Palsson, Master. Gosta Leonard   2.0
16                Rice, Master. Eugene   2.0
50          Panula, Master. Juha Niilo   7.0
59  Goodwin, Master. William Frederick  11.0
63               Skoog, Master. Harald   4.0