Day 2, Topic 5: The .query() Method

In [2]:
import pandas as pd
df = pd.read_csv('titanic.csv')

In [4]:
#Basic Syntax
older = df.query("Age > 30")
older[['Name', 'Age']].head()

                                                 Name   Age
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                            Allen, Mr. William Henry  35.0
6                             McCarthy, Mr. Timothy J  54.0
11                           Bonnell, Miss. Elizabeth  58.0

In [5]:
#Multiple Conditions
first_class_womean = df.query("Sex == 'female' and Pclass == 1")
first_class_womean[['Name', 'Sex', 'Pclass']].head()

                                                 Name     Sex  Pclass
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female       1
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female       1
11                           Bonnell, Miss. Elizabeth  female       1
31     Spencer, Mrs. William Augustus (Marie Eugenie)  female       1
52           Harper, Mrs. Henry Sleeper (Myna Haxtun)  female       1

In [6]:
#Using Variables in Queries
min_age = 50
max_fare = 100 
result = df.query("Age > @min_age and Fare < @max_fare")
result[['Name', 'Age', 'Fare']].head()

                                Name   Age     Fare
6            McCarthy, Mr. Timothy J  54.0  51.8625
11          Bonnell, Miss. Elizabeth  58.0  26.5500
15  Hewlett, Mrs. (Mary D Kingcome)   55.0  16.0000
33             Wheadon, Mr. Edward H  66.0  10.5000
54    Ostby, Mr. Engelhart Cornelius  65.0  61.9792

In [7]:
#Practice Activity: .query() Method
import pandas as pd
df = pd.read_csv('titanic.csv')

In [8]:
#Task 1: Use .query() to filter passengers older than 60. Display Name and Age.

older = df.query("Age > 60")
older[['Name', 'Age']].head()

                               Name   Age
33            Wheadon, Mr. Edward H  66.0
54   Ostby, Mr. Engelhart Cornelius  65.0
96        Goldschmidt, Mr. George B  71.0
116            Connors, Mr. Patrick  70.5
170       Van der hoef, Mr. Wyckoff  61.0

In [9]:
#Task 2: Use .query() to filter female passengers who survived. How many are there? (Use .shape[0] or len())
survived_womens = df.query("Sex == 'female' and Survived == 1")
len(survived_womens)

233

In [11]:
#Task 3: Use .query() with a variable. Create a variable min_fare = 200. Then filter passengers who paid
# a fare greater than min_fare. Display Name and Fare.

min_fare = 200
fare = df.query("Fare > @min_fare")
fare[['Name', 'Fare']].head()

                                                Name      Fare
27                    Fortune, Mr. Charles Alexander  263.0000
88                        Fortune, Miss. Mabel Helen  263.0000
118                         Baxter, Mr. Quigg Edmond  247.5208
258                                 Ward, Miss. Anna  512.3292
299  Baxter, Mrs. James (Helene DeLaudeniere Chaput)  247.5208

In [12]:
#Task 4: Use .query() to find passengers in first or second class (Pclass in [1, 2]). Display Name and Pclass.
passen = df.query("Pclass in [1, 2]")
passen[['Name', 'Pclass']].head()

                                                 Name  Pclass
1   Cumings, Mrs. John Bradley (Florence Briggs Th...       1
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
6                             McCarthy, Mr. Timothy J       1
9                 Nasser, Mrs. Nicholas (Adele Achem)       2
11                           Bonnell, Miss. Elizabeth       1

In [14]:
"""Task 5 (Bonus): Use .query() to find passengers whose name contains 'Mr.'
and who did not survive. Display Name and Survived."""

passen_2 = df[df['Name'].str.contains('Mr.')].query("Survived == 0")
passen_2[['Name', 'Survived']].head()

                              Name  Survived
0          Braund, Mr. Owen Harris         0
4         Allen, Mr. William Henry         0
5                 Moran, Mr. James         0
6          McCarthy, Mr. Timothy J         0
12  Saundercock, Mr. William Henry         0

In [15]:
#Day 2, Topic 6: .isin() and .between()

import pandas as pd

df = pd.read_csv('titanic.csv')

In [16]:
#.isin() – Filter by Membership in a List

mask = df['Embarked'].isin(['C', 'Q'])
cherbourg_queenstown = df[mask]
cherbourg_queenstown[['Name', 'Embarked']].head()

                                                 Name Embarked
1   Cumings, Mrs. John Bradley (Florence Briggs Th...        C
5                                    Moran, Mr. James        Q
9                 Nasser, Mrs. Nicholas (Adele Achem)        C
16                               Rice, Master. Eugene        Q
19                            Masselmani, Mrs. Fatima        C

In [18]:
#.isin() with Multiple Values
upper_class = df[df['Pclass'].isin([1, 2])]

specific_ids = df[df['PassengerId'].isin([10, 20, 30, 40, 50])]

In [19]:
#Negating .isin() with ~
# Passengers NOT from Southampton

not_southampton = df[~df['Embarked'].isin(['S'])]

In [20]:
#.between() – Filter Numeric Ranges
# Passengers aged 20 to 30 (inclusive)

young_adults = df[df['Age'].between(10, 20)]
young_adults[['Name', 'Age']].head()

                                    Name   Age
9    Nasser, Mrs. Nicholas (Adele Achem)  14.0
12        Saundercock, Mr. William Henry  20.0
14  Vestrom, Miss. Hulda Amanda Adolfina  14.0
22           McGowan, Miss. Anna "Annie"  15.0
27        Fortune, Mr. Charles Alexander  19.0

In [21]:
#Combining .isin() and .between() with Other Conditions
mask = df['Pclass'].isin([1, 2]) & df['Age'].between(30, 50)
result = df[mask]
result[['Name', 'Age', 'Pclass']].head()

                                                 Name   Age  Pclass
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0       1
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0       1
20                               Fynney, Mr. Joseph J  35.0       2
21                              Beesley, Mr. Lawrence  34.0       2
30                           Uruchurtu, Don. Manuel E  40.0       1

In [22]:
#Practice Activity: .isin() and .between()
import pandas as pd
df = pd.read_csv('titanic.csv')

In [24]:
"""Task 1: Use .isin() to filter passengers who embarked at 'C' (Cherbourg) or 'Q' (Queenstown). 
Display the Name and Embarked columns. How many such passengers are there?"""
mask = df['Embarked'].isin(['C', 'Q'])
result = df[mask]
result[['Name', 'Embarked']].head()

                                                 Name Embarked
1   Cumings, Mrs. John Bradley (Florence Briggs Th...        C
5                                    Moran, Mr. James        Q
9                 Nasser, Mrs. Nicholas (Adele Achem)        C
16                               Rice, Master. Eugene        Q
19                            Masselmani, Mrs. Fatima        C

In [25]:
#Task 2: Use ~ with .isin() to filter passengers who are not in first or second class. Display Name and Pclass.

mask = ~df['Pclass'].isin([1, 2])
result = df[mask]
result[['Name', 'Pclass']].head()

                             Name  Pclass
0         Braund, Mr. Owen Harris       3
2          Heikkinen, Miss. Laina       3
4        Allen, Mr. William Henry       3
5                Moran, Mr. James       3
7  Palsson, Master. Gosta Leonard       3

In [28]:
#Task 3: Use .between() to filter passengers aged 18 to 25 (inclusive). Display Name and Age. 
# How many young adults are there?
mask = df['Age'].between(18, 25)
result = df[mask]
result[['Name', 'Age']].head()
len(result)

188

In [29]:
#Task 4: Use .between() with inclusive='left' to filter passengers aged 18 or older but under 30. 
#(i.e., age >= 18 and < 30). Display Name and Age.

mask = df['Age'].between(18, 30, inclusive='left')
result = df[mask]
result[['Name', 'Age']].head()

                                                 Name   Age
0                             Braund, Mr. Owen Harris  22.0
2                              Heikkinen, Miss. Laina  26.0
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
12                     Saundercock, Mr. William Henry  20.0
23                       Sloper, Mr. William Thompson  28.0

In [30]:
"""Task 5: Combine .isin() and .between(): Find female passengers in first or second class with age between 25 and 40.
Display Name, Sex, Pclass, and Age."""

mask = (df['Sex'] == 'female') & (df['Pclass'].isin([1, 2])) & (df['Age'].between(25, 40))
result = df[mask]
result[['Name', 'Sex', 'Pclass', 'Age']].head()

                                                 Name     Sex  Pclass   Age
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female       1  38.0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female       1  35.0
41  Turpin, Mrs. William John Robert (Dorothy Ann ...  female       2  27.0
53  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female       2  29.0
61                                Icard, Miss. Amelie  female       1  38.0