Day 2, Topic 7: String Methods (.str Accessor)

In [1]:
import pandas as pd
df = pd.read_csv('titanic.csv')

In [3]:
#Filtering with .str.contains()
# Passengers with 'Mrs' in their name
mrs_mask = df['Name'].str.contains('Mrs', case=False)
mrs_passengers = df[mrs_mask]
mrs_passengers[['Name']].head()

                                                 Name
1   Cumings, Mrs. John Bradley (Florence Briggs Th...
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                 Nasser, Mrs. Nicholas (Adele Achem)
15                   Hewlett, Mrs. (Mary D Kingcome)

In [4]:
#Extracting Substrings with .str.extract()
df['Title'] = df['Name'].str.extract(r'([A-Za-z]+)\.')
df[['Name', 'Title']].head()

                                                Name Title
0                            Braund, Mr. Owen Harris    Mr
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   Mrs
2                             Heikkinen, Miss. Laina  Miss
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   Mrs
4                           Allen, Mr. William Henry    Mr

In [6]:
#Splitting Strings with .str.split()
split_names = df['Name'].str.split(',', expand=True)
df['LastName'] = split_names[0]
df['FirstName'] = split_names[1].str.strip()
df[['Name', 'LastName', 'FirstName']].head()

# Get length of last name
df['LastNameLength'] = df['LastName'].str.len()

# Clean and lowercase
df['CleanTitle'] = df['Title'].str.strip().str.lower()

In [7]:
#Practice Activity: String Methods

import pandas as pd

df = pd.read_csv('titanic.csv')

In [10]:
"""Task 1: Filter the DataFrame to show only passengers whose name contains 'Miss'. 
Display the Name column. How many are there?
"""

miss_mask = df['Name'].str.contains('Miss')
result = df[miss_mask]
result[['Name']].head()
len(result)

182

In [12]:
#Task 2: Filter passengers whose name starts with 'A'. Display Name. How many?

name_mask = df['Name'].str.startswith('A')
result = df[name_mask]
result[['Name']].head()
len(result)

51

In [15]:
"""Task 3: Create a new column NameLength that contains the number of characters in 
each passenger's full name (including spaces). What is the average name length?"""

df['NameLength'] = df['Name'].str.len()
df[['Name', 'NameLength']].head()
avg_name_length = df['NameLength'].mean()
avg_name_length

np.float64(26.9652076318743)

In [17]:
"""Task 4: Extract the title (e.g., 'Mr', 'Mrs', 'Miss', 'Master') from the Name column into a new column called Title. 
Use .str.extract() with the pattern r'([A-Za-z]+)\.'. Display the value counts of Title."""


df['Title'] = df['Name'].str.extract(r'([A-Za-z]+)\.')
df[['Name', 'Title']].head()
df['Title'].value_counts()

Title
Mr          517
Miss        182
Mrs         125
Master       40
Dr            7
Rev           6
Mlle          2
Major         2
Col           2
Countess      1
Capt          1
Ms            1
Sir           1
Lady          1
Mme           1
Don           1
Jonkheer      1
Name: count, dtype: int64

In [19]:
"""Task 5 (Bonus): Filter passengers whose title is 'Mr' AND who did not survive. Display Name and Survived. 
How many such passengers are there?"""

mr_not_survived = df[(df['Title'] == 'Mr') & (df['Survived'] == 0)]
mr_not_survived[['Name', 'Survived']].head()
len(mr_not_survived)

436

In [20]:
#Day 2, Topic 8: .where() and .mask()

import pandas as pd

df = pd.read_csv('titanic.csv')

In [22]:
#.where() – Keep Values Where Condition is True

adult_ages = df['Age'].where(df['Age'] > 18, other='underage')
adult_ages.head(10)

0        22.0
1        38.0
2        26.0
3        35.0
4        35.0
5    underage
6        54.0
7    underage
8        27.0
9    underage
Name: Age, dtype: object

In [24]:
# Replace ages ≤ 18 with 'Child'
age_status = df['Age'].mask(df['Age'] <= 18, 'Child')
print(age_status.head(10))

0     22.0
1     38.0
2     26.0
3     35.0
4     35.0
5      NaN
6     54.0
7    Child
8     27.0
9    Child
Name: Age, dtype: object

In [25]:
# Keep only numeric columns, replace non-numeric with NaN
numeric_df = df.select_dtypes(include='number')
masked_df = numeric_df.where(numeric_df > 0)
print(masked_df.head())

   PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0            1       NaN       3  22.0    1.0    NaN   7.2500
1            2       1.0       1  38.0    1.0    NaN  71.2833
2            3       1.0       3  26.0    NaN    NaN   7.9250
3            4       1.0       1  35.0    1.0    NaN  53.1000
4            5       NaN       3  35.0    NaN    NaN   8.0500

In [26]:
# Practice Activity: .where() and .mask()

import pandas as pd

df = pd.read_csv('titanic.csv')

In [28]:
"""Task 1: Use .where() to create a Series adult_fares that contains the Fare for passengers aged 18 or older, 
and NaN for those under 18. Display the first 10 rows."""

print("=== Task 1: adult_fares ===")
adult_fares = df['Fare'].where(df['Age'] >= 18)
print(adult_fares.head(10))

=== Task 1: adult_fares ===
0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
5        NaN
6    51.8625
7        NaN
8    11.1333
9        NaN
Name: Fare, dtype: float64

In [31]:
"""Task 2: Use .mask() to replace all fares greater than 100 with the string 'Expensive'. 
Keep other fares as their original values. Display the first 10 rows."""


result = df['Fare'].mask(df['Fare'] > 100, "Expensive")
result.head(30)

0          7.25
1       71.2833
2         7.925
3          53.1
4          8.05
5        8.4583
6       51.8625
7        21.075
8       11.1333
9       30.0708
10         16.7
11        26.55
12         8.05
13       31.275
14       7.8542
15         16.0
16       29.125
17         13.0
18         18.0
19        7.225
20         26.0
21         13.0
22       8.0292
23         35.5
24       21.075
25      31.3875
26        7.225
27    Expensive
28       7.8792
29       7.8958
Name: Fare, dtype: object

In [35]:
"""Task 3: Use .where() on the Sex column to keep only 'female' values and replace 'male' with NaN. 
Display the value counts of the result."""

result = df['Sex'].where(df['Sex'] == 'female')
result.value_counts(dropna=False)

Sex
NaN       577
female    314
Name: count, dtype: int64

In [36]:
#Task 4: Use .mask() to replace all ages less than 18 with 'Minor'. Show the first 10 rows.
result = df['Age'].mask(df['Age'] < 18, 'Minor')
result.head(10)

0     22.0
1     38.0
2     26.0
3     35.0
4     35.0
5      NaN
6     54.0
7    Minor
8     27.0
9    Minor
Name: Age, dtype: object

In [37]:
"""Task 5 (Bonus): Create a new column SurvivedText that contains 'Survived' where Survived == 1 and 
'Perished' where Survived == 0. Use either .where() or .mask()"""

df['SurvivedText'] = df['Survived'].mask(df['Survived'] == 1, 'Survived').mask(df['Survived'] == 0, 'Perished')
print(df[['Survived', 'SurvivedText']].head(10))

   Survived SurvivedText
0         0     Perished
1         1     Survived
2         1     Survived
3         1     Survived
4         0     Perished
5         0     Perished
6         0     Perished
7         0     Perished
8         1     Survived
9         1     Survived

In [38]:
#Day 2, Topic 9: Filtering with .filter()
import pandas as pd

df = pd.read_csv('titanic.csv')

In [39]:
#Selecting Columns by Name Pattern
name_columns = df.filter(like='Name')
name_columns.head()

                                                Name
0                            Braund, Mr. Owen Harris
1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2                             Heikkinen, Miss. Laina
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                           Allen, Mr. William Henry

In [40]:
#Using regex for Powerful Pattern Matching
ps_columns = df.filter(regex='^(P|S)')
ps_columns.columns.to_list()

['PassengerId', 'Survived', 'Pclass', 'Sex', 'SibSp', 'Parch']

In [41]:
#Using items to Select Exact Column Names
selected = df.filter(items=['Name', 'Age', 'Fare'])
selected.head()

                                                Name   Age     Fare
0                            Braund, Mr. Owen Harris  22.0   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                             Heikkinen, Miss. Laina  26.0   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                           Allen, Mr. William Henry  35.0   8.0500

In [42]:
#Practice Activity: .filter()
import pandas as pd
df = pd.read_csv('titanic.csv')

In [44]:
#Task 1: Use .filter(like='ame') to select all columns containing the substring 'ame'. What columns are returned?
substring = df.filter(like='ame')
substring.head()

                                                Name
0                            Braund, Mr. Owen Harris
1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2                             Heikkinen, Miss. Laina
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                           Allen, Mr. William Henry

In [45]:
#Task 2: Use .filter(regex='e$') to select all columns whose names end with the letter 'e'. Display their names.
selected = df.filter(regex='e$')
selected.columns.tolist()

['Name', 'Age', 'Fare']

In [47]:
#Task 3: Use .filter(items=['Survived', 'Pclass', 'Sex']) to create a smaller DataFrame. Display its first 3 rows.

items = df.filter(items=['Survived', 'Pclass', 'Sex'])
items.head()

   Survived  Pclass     Sex
0         0       3    male
1         1       1  female
2         1       3  female
3         1       1  female
4         0       3    male

In [49]:
#Task 4: Chain .filter() and .describe(): Select all columns that start with 'S' and show their summary statistics.
df.filter(regex='^S').describe()

         Survived       SibSp
count  891.000000  891.000000
mean     0.383838    0.523008
std      0.486592    1.102743
min      0.000000    0.000000
25%      0.000000    0.000000
50%      0.000000    0.000000
75%      1.000000    1.000000
max      1.000000    8.000000

In [50]:
# Create a new DataFrame with additional columns
new_df = df.copy()
new_df['Score_Math'] = 85
new_df['Score_Reading'] = 90
new_df['Score_Writing'] = 88
new_df['Grade_Level'] = 'A'

# Filter only score columns and compute row-wise mean
score_cols = new_df.filter(like='Score')
new_df['Score_Avg'] = score_cols.mean(axis=1)

print(new_df[['Score_Math', 'Score_Reading', 'Score_Writing', 'Score_Avg']].head())

   Score_Math  Score_Reading  Score_Writing  Score_Avg
0          85             90             88  87.666667
1          85             90             88  87.666667
2          85             90             88  87.666667
3          85             90             88  87.666667
4          85             90             88  87.666667