In [28]:
#Day 9, Topic 1: Memory Optimization
import pandas as pd
df = pd.read_csv('titanic.csv')

In [29]:
#Checking Memory Usage
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 285.6 KB

In [30]:
#Strategy 1 – category Dtype for Object Columns
df['Sex'] = df['Sex'].astype('category')
df['Embarked'] = df['Embarked'].astype('category')
df['Pclass'] = df['Pclass'].astype('category')

df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    category
 3   Name         891 non-null    object
 4   Sex          891 non-null    category
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    category
dtypes: category(3), float64(2), int64(4), object(3)
memory usage: 191.7 KB

In [31]:
#Strategy 2 – Downcasting Numeric Types
df['PassengerId'] = pd.to_numeric(df['PassengerId'], downcast='integer')
df['Survived'] = pd.to_numeric(df['Survived'], downcast='integer')
df['Sibsp'] = pd.to_numeric(df['SibSp'], downcast='integer')
df['Parch'] = pd.to_numeric(df['Parch'], downcast='integer')

df['Age'] = pd.to_numeric(df['Age'], downcast='float')
df['Fare'] = pd.to_numeric(df['Fare'], downcast='float')

df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int16
 1   Survived     891 non-null    int8
 2   Pclass       891 non-null    category
 3   Name         891 non-null    object
 4   Sex          891 non-null    category
 5   Age          714 non-null    float32
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int8
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float32
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    category
 12  Sibsp        891 non-null    int8
dtypes: category(3), float32(2), int16(1), int64(1), int8(3), object(3)
memory usage: 168.2 KB

In [32]:
#Strategy 3 – Load Only What You Need
df_subset = pd.read_csv('titanic.csv', usecols=['PassengerId', 'Survived', 'Pclass'],
                                        dtype={'PassengerId': 'int16', 'Survived': 'int8', 'Pclass': 'category'})

In [33]:
#Practice Activity: Memory Optimization
import pandas as pd
df = pd.read_csv('titanic.csv')

In [34]:
#Task 1: Print the baseline memory usage using info(memory_usage='deep'). Note the total memory used.

baseline_mem = df.memory_usage(deep=True).sum()
baseline_mem

np.int64(292464)

In [35]:
"""Task 2: Convert Sex, Embarked, and Pclass to category dtype. Print the new memory usage. 
How much did you save on these columns?"""

# Convert to category
for col in ['Sex', 'Embarked', 'Pclass']:
    df[col] = df[col].astype('category')

print("\n--- Memory Usage After Categorical Conversion ---")
df.info(memory_usage='deep')
category_mem = df.memory_usage(deep=True).sum()

savings = baseline_mem - category_mem
print(f"\nSaved {savings / 1024:.2f} KB on these three columns.")

--- Memory Usage After Categorical Conversion ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    category
 3   Name         891 non-null    object
 4   Sex          891 non-null    category
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    category
dtypes: category(3), float64(2), int64(4), object(3)
memory usage: 191.7 KB

Saved 93.96 KB on these three columns.

In [36]:
# Downcast integers and floats
for col in ['PassengerId', 'Survived', 'SibSp', 'Parch']:
    df[col] = pd.to_numeric(df[col], downcast='integer')

for col in ['Age', 'Fare']:
    df[col] = pd.to_numeric(df[col], downcast='float')

final_mem = df.memory_usage(deep=True).sum()
reduction_pct = (1 - (final_mem / baseline_mem)) * 100

print(f"\nFinal Memory Usage: {final_mem / 1024:.2f} KB")
print(f"Total Reduction: {reduction_pct:.2f}%")

Final Memory Usage: 161.20 KB
Total Reduction: 43.56%

In [37]:
def optimize_dtypes(df):
    start_mem = df.memory_usage(deep=True).sum()
    
    for col in df.columns:
        col_type = df[col].dtype
        
        # 1. Convert objects to category if unique values < 50%
        if col_type == 'object':
            num_unique = df[col].nunique()
            num_total = len(df)
            if (num_unique / num_total) < 0.5:
                df[col] = df[col].astype('category')
                
        # 2. Downcast numeric columns
        elif 'int' in str(col_type):
            df[col] = pd.to_numeric(df[col], downcast='integer')
        elif 'float' in str(col_type):
            df[col] = pd.to_numeric(df[col], downcast='float')
            
    end_mem = df.memory_usage(deep=True).sum()
    print(f"Optimization complete. Saved {(start_mem - end_mem) / 1024:.2f} KB.")
    return df

# Test the function
df_optimized = optimize_dtypes(df.copy())

Optimization complete. Saved 18.62 KB.

In [39]:
#Day 9, Topic 2: Method Chaining
import pandas as pd

In [41]:
#method chaining:
df = (pd.read_csv('titanic.csv')
     .assign(FamilySize= lambda x: x['SibSp'] + x['Parch'] + 1)
     .rename(columns={'Sex': 'Gender'})
     .drop(columns=['Ticket', 'Cabin'])
     .query('Age > 18')
)

df.head()

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Fare,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,S,1

In [43]:
#Using .pipe() for Custom Functions
def add_family_size(df):
    df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
    return df

def categorize_age(df):
    df['AgeGroup'] = pd.cut(df['Age'], bins=[0, 18, 35, 60, 100],
                                       labels=['Child', 'Young Adult', 'Adult', 'Senior'])
    return df


df = (pd.read_csv('titanic.csv')
     .pipe(add_family_size)
     .pipe(categorize_age)
     .query('AgeGroup == "Adult"')
     .head()
)

df[['Name', 'Age', 'AgeGroup']]

                                                 Name   Age AgeGroup
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0    Adult
6                             McCarthy, Mr. Timothy J  54.0    Adult
11                           Bonnell, Miss. Elizabeth  58.0    Adult
13                        Andersson, Mr. Anders Johan  39.0    Adult
15                   Hewlett, Mrs. (Mary D Kingcome)   55.0    Adult

In [44]:
import numpy as np
df = pd.read_csv('titanic.csv').assign(
    FamilySize = lambda x: x['SibSp'] + x['Parch'] + 1,
    IsAlone = lambda x: x['FamilySize'] == 1,
    FareLog = lambda x: np.log1p(x['Fare'])
)

df[['FamilySize', 'IsAlone', 'FareLog']].head()

   FamilySize  IsAlone   FareLog
0           2    False  2.110213
1           2    False  4.280593
2           1     True  2.188856
3           2    False  3.990834
4           1     True  2.202765

In [45]:
#Chaining After GroupBy
result = (pd.read_csv('titanic.csv')
         .groupby('Pclass')
         .agg(AvgFare=('Fare', 'mean'), Count=('PassengerId', 'count'))
         .reset_index()
         .rename(columns={'AvgFare': 'Average_Fare'})
         .query('Count > 100')
)

result

   Pclass  Average_Fare  Count
0       1     84.154687    216
1       2     20.662183    184
2       3     13.675550    491

In [46]:
#Using loc in a Chain
df = pd.read_csv('titanic.csv').pipe(lambda x: x.loc[x['Pclass'] == 1, ['Name', 'Age']]).head()

In [47]:
#Practice Activity: Method Chaining
import pandas as pd
import numpy as np

In [49]:
df = (pd.read_csv('titanic.csv')
     .assign(FamilySize = lambda x: x['SibSp'] + x['Parch'] + 1)
     .rename(columns={'Sex': 'Gender'})
     .drop(columns=['Ticket', 'Cabin'])
     .query("Age > 12 and Fare < 500")
     .groupby(['Pclass', 'Gender'])['Fare'].mean()
     .reset_index()
     .rename(columns={'Fare': 'Average_Fare'})
)

df

   Pclass  Gender  Average_Fare
0       1  female    102.548846
1       1    male     60.493273
2       2  female     20.932576
3       2    male     20.493842
4       3  female     14.165351
5       3    male     10.504036