In [64]:
#Day 6, Topic 3: Date Arithmetic and Timedeltas

In [65]:
import pandas as pd
import numpy as np

df = pd.read_csv('titanic.csv')
# Simulate booking date and departure date
departure = pd.to_datetime('1912-04-15')
np.random.seed(42)
df['Booking_Date'] = departure - pd.Timedelta(days=30) + pd.to_timedelta(np.random.randint(-5, 5, size=len(df)), unit='D')
df['Departure_Date'] = departure

In [66]:
#Subtracting Dates – Time Differences
df['Days_Ahead'] = df['Departure_Date'] - df['Booking_Date']
df[['Booking_Date', 'Departure_Date', 'Days_Ahead']].head()

  Booking_Date Departure_Date Days_Ahead
0   1912-03-17     1912-04-15    29 days
1   1912-03-14     1912-04-15    32 days
2   1912-03-18     1912-04-15    28 days
3   1912-03-15     1912-04-15    31 days
4   1912-03-17     1912-04-15    29 days

In [67]:
#Adding/Subtracting Time with pd.Timedelta
df['Booking_Plus_Week'] = df['Booking_Date'] + pd.Timedelta(days=7)
df[['Booking_Date', 'Booking_Plus_Week']].head()

  Booking_Date Booking_Plus_Week
0   1912-03-17        1912-03-24
1   1912-03-14        1912-03-21
2   1912-03-18        1912-03-25
3   1912-03-15        1912-03-22
4   1912-03-17        1912-03-24

In [68]:
#Creating a Timedelta from a Column
df['Offset_Days'] = np.random.randint(1, 10, size=len(df))
df['New_Date'] = df['Booking_Date'] + pd.to_timedelta(df['Offset_Days'], unit='D')
df[['Booking_Date', 'New_Date']].head()

  Booking_Date   New_Date
0   1912-03-17 1912-03-21
1   1912-03-14 1912-03-15
2   1912-03-18 1912-03-23
3   1912-03-15 1912-03-24
4   1912-03-17 1912-03-18

In [69]:
#Comparing Dates
late_bookings = df[df['Days_Ahead'] < pd.Timedelta(days=30)]
len(late_bookings)

349

In [70]:
#Practice Activity: Date Arithmetic
import pandas as pd
import numpy as np


df = pd.read_csv('titanic.csv')

departure = pd.to_datetime('1912-04-15')
np.random.seed(42)
df['Booking_Date'] = departure - pd.Timedelta(days=30) + pd.to_timedelta(np.random.randint(-10, 10, size=len(df)), unit='D')
df['Departure_Date'] = departure

In [71]:
"""Task 1: Create a new column Days_Before that is the number of days between Booking_Date 
and Departure_Date as an integer (use .dt.days)."""

df['Days_Before'] = df['Departure_Date'] - df['Booking_Date']
df['Days_Before'] = df['Days_Before'].dt.days
df[['Booking_Date', 'Departure_Date', 'Days_Before']].head()

  Booking_Date Departure_Date  Days_Before
0   1912-03-12     1912-04-15           34
1   1912-03-25     1912-04-15           21
2   1912-03-20     1912-04-15           26
3   1912-03-16     1912-04-15           30
4   1912-03-13     1912-04-15           33

In [72]:
#Task 2: Create a column Booking_2Weeks_Later that is Booking_Date plus 14 days.

df['Booking_2Weeks_Later'] = df['Booking_Date'] + pd.Timedelta(days=14)
df[['Booking_Date', 'Booking_2Weeks_Later']].head()

  Booking_Date Booking_2Weeks_Later
0   1912-03-12           1912-03-26
1   1912-03-25           1912-04-08
2   1912-03-20           1912-04-03
3   1912-03-16           1912-03-30
4   1912-03-13           1912-03-27

In [73]:
"""Task 3: Create a Boolean column Is_Early_Bird that is True if the booking was made more than 35 
days before departure, False otherwise."""
# 1. Calculate the difference (this creates a Timedelta Series)
# 2. Compare it to a Timedelta of 35 days
df['Is_Early_Bird'] = (df['Departure_Date'] - df['Booking_Date']) > pd.Timedelta(days=35)

# Display a sample of the results
print(df[['Booking_Date', 'Departure_Date', 'Is_Early_Bird']].head())

# Check how many passengers qualified
print(f"\nNumber of Early Birds: {df['Is_Early_Bird'].sum()}")

  Booking_Date Departure_Date  Is_Early_Bird
0   1912-03-12     1912-04-15          False
1   1912-03-25     1912-04-15          False
2   1912-03-20     1912-04-15          False
3   1912-03-16     1912-04-15          False
4   1912-03-13     1912-04-15          False

Number of Early Birds: 258

In [74]:
"""Task 4: Filter the DataFrame to show only passengers who booked exactly 30 days before departure. 
How many are there? (Hint: compare Days_Before == 30.)"""

exact_pass = df[df['Days_Before'] == 30]

len(exact_pass)

35

In [75]:
"""Task 5 (Bonus): Calculate the average number of days before departure that passengers booked, 
grouped by Pclass. Which class booked the earliest on average?"""

avg_days = df.groupby('Pclass')['Days_Before'].mean()
avg_days

Pclass
1    31.324074
2    30.125000
3    30.841141
Name: Days_Before, dtype: float64

In [76]:
#Day 6, Topic 4: Resampling Time Series
import pandas as pd
import numpy as np

df = pd.read_csv('titanic.csv')

# Simulate a 'Booking_Date' column for each passenger (already done in earlier topics)
departure = pd.to_datetime('1912-04-15')
np.random.seed(42)
df['Booking_Date'] = departure - pd.Timedelta(days=30) + pd.to_timedelta(np.random.randint(-10, 10, size=len(df)), unit='D')

In [77]:
daily_sampling = df.resample('D', on='Booking_Date')['PassengerId'].count()

daily_sampling.head(10)

Booking_Date
1912-03-06    58
1912-03-07    44
1912-03-08    56
1912-03-09    43
1912-03-10    57
1912-03-11    41
1912-03-12    40
1912-03-13    46
1912-03-14    40
1912-03-15    36
Freq: D, Name: PassengerId, dtype: int64

In [78]:
#Example: Weekly bookings
weekly_booking = df.resample('W-MON', on='Booking_Date')['PassengerId'].count()
weekly_booking

Booking_Date
1912-03-11    299
1912-03-18    289
1912-03-25    303
Freq: W-MON, Name: PassengerId, dtype: int64

In [79]:
#Multiple Aggregations
fare_stats = df.resample('W', on='Booking_Date')['Fare'].agg(['sum', 'mean', 'count'])
fare_stats

                    sum       mean  count
Booking_Date
1912-03-10    9568.3045  37.086452    258
1912-03-17    8344.3954  29.278580    285
1912-03-24    9736.5911  31.715280    307
1912-03-31    1044.6583  25.479471     41

In [80]:
#Resampling with a Datetime Index
df_indexed = df.set_index('Booking_Date')
monthly_avg_fare = df_indexed['Fare'].resample('M').mean()
monthly_avg_fare

C:\Users\Faizan Toheed\AppData\Local\Temp\ipykernel_9864\3369247217.py:3: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_avg_fare = df_indexed['Fare'].resample('M').mean()

Booking_Date
1912-03-31    32.204208
Freq: ME, Name: Fare, dtype: float64

In [81]:
# Create a small daily series
daily = df.resample('D', on='Booking_Date')['Fare'].mean()
# Upsample to 12-hour intervals
upsampled = daily.resample('12H').ffill()
print(upsampled.head(10))

Booking_Date
1912-03-06 00:00:00    33.257255
1912-03-06 12:00:00    33.257255
1912-03-07 00:00:00    41.820455
1912-03-07 12:00:00    41.820455
1912-03-08 00:00:00    37.349409
1912-03-08 12:00:00    37.349409
1912-03-09 00:00:00    29.873837
1912-03-09 12:00:00    29.873837
1912-03-10 00:00:00    42.511260
1912-03-10 12:00:00    42.511260
Freq: 12h, Name: Fare, dtype: float64

C:\Users\Faizan Toheed\AppData\Local\Temp\ipykernel_9864\103133885.py:4: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  upsampled = daily.resample('12H').ffill()

In [82]:
#Practice Activity: Resampling
import pandas as pd
import numpy as np

df = pd.read_csv('titanic.csv')

departure = pd.to_datetime('1912-04-15')
np.random.seed(42)
df['Booking_Date'] = departure - pd.Timedelta(days=30) + pd.to_timedelta(np.random.randint(-10, 10, size=len(df)), unit='D')

In [83]:
"""Task 1: Resample the data to weekly frequency (ending on Sunday, 'W') 
and compute the total Fare collected each week. Display the result."""

weekly = df.resample('W', on='Booking_Date')['Fare'].sum()
weekly

Booking_Date
1912-03-10    9568.3045
1912-03-17    8344.3954
1912-03-24    9736.5911
1912-03-31    1044.6583
Freq: W-SUN, Name: Fare, dtype: float64

In [84]:
"""Task 2: Resample to monthly frequency ('M') and compute both the average
 Fare and number of bookings in a single .agg() call."""

montly = df.resample('ME', on='Booking_Date')['Fare', 'PassengerId'].agg({'Fare': 'mean', 'PassengerId': 'count'})
montly

                   Fare  PassengerId
Booking_Date
1912-03-31    32.204208          891

In [90]:
"""Task 3: Set Booking_Date as the index, then resample to daily frequency and 
count how many passengers booked each day. Fill any missing days with 0 
(hint: use .resample('D').count() and then .fillna(0))."""

df_indexed = df.set_index('Booking_Date')
daily = df_indexed.resample('D')['PassengerId'].count().fillna(0)

daily.head(10)

Booking_Date
1912-03-06    58
1912-03-07    44
1912-03-08    56
1912-03-09    43
1912-03-10    57
1912-03-11    41
1912-03-12    40
1912-03-13    46
1912-03-14    40
1912-03-15    36
Freq: D, Name: PassengerId, dtype: int64

In [92]:
"""Task 4 (Bonus): Compute a 7‑day rolling average of daily booking counts. 
(We'll preview rolling windows next, but try: daily_bookings.rolling(7).mean())."""

rolling_7d = daily.rolling(window=7).mean()
rolling_7d.head(10)

Booking_Date
1912-03-06          NaN
1912-03-07          NaN
1912-03-08          NaN
1912-03-09          NaN
1912-03-10          NaN
1912-03-11          NaN
1912-03-12    48.428571
1912-03-13    46.714286
1912-03-14    46.142857
1912-03-15    43.285714
Freq: D, Name: PassengerId, dtype: float64