In [63]:
#Day 6, Topic 1: Converting to Datetime

import pandas as pd

In [64]:
#Basic pd.to_datetime()
dates = pd.Series(['2024-01-01', '2024-02-01', '2024-03-01'])
print(dates.dtype)

datetime_dates = pd.to_datetime(dates)
print(datetime_dates.dtype)
datetime_dates

object
datetime64[ns]

0   2024-01-01
1   2024-02-01
2   2024-03-01
dtype: datetime64[ns]

In [65]:
#Handling Different Date Formats
dates_uk = pd.Series(['01/01/2024', '02/03/2025']) #DD/MM/YYYY
datetime_dates = pd.to_datetime(dates_uk, format='%d/%m/%Y')
datetime_dates

0   2024-01-01
1   2025-03-02
dtype: datetime64[ns]

In [66]:
#The errors Parameter
messy_date = pd.Series(['2024/02/01', 'Not a date', '2024/03/03'])
clean_date = pd.to_datetime(messy_date, errors='coerce')
clean_date

0   2024-02-01
1          NaT
2   2024-03-03
dtype: datetime64[ns]

In [67]:
#Converting DataFrame Columns
df = pd.DataFrame({
    'Name': ['Faizan', 'Ali'],
    'Join_Date': ['2023-01-23', '2024-11-9']
})

df['Join_Date'] = pd.to_datetime(df['Join_Date'])
df

     Name  Join_Date
0  Faizan 2023-01-23
1     Ali 2024-11-09

In [68]:
#Working with Timestamps
single_date = pd.to_datetime('2026-04-22')

print(single_date.year)
print(single_date.month)
print(single_date.day)
print(single_date.dayofweek + 1)

2026
4
22
3

In [69]:
#Practice Activity: Datetime Conversion
import pandas as pd

data = {
    'Event': ['Conference', 'Workshop', 'Seminar', 'Meetup'],
    'Date_Str': ['2024-03-15', '2024/04/20', 'Invalid', '15-05-2024']
}
df = pd.DataFrame(data)
df

        Event    Date_Str
0  Conference  2024-03-15
1    Workshop  2024/04/20
2     Seminar     Invalid
3      Meetup  15-05-2024

In [70]:
"""Task 1: Convert the Date_Str column to datetime using pd.to_datetime() with errors='coerce'. 
Display the DataFrame and note which row becomes NaT."""

result = pd.to_datetime(df['Date_Str'], errors='coerce')

result

0   2024-03-15
1          NaT
2          NaT
3          NaT
Name: Date_Str, dtype: datetime64[ns]

In [71]:

"""Task 2: The valid dates are in mixed formats. Use the format parameter to correctly 
parse the third row ('15-05-2024' as '%d-%m-%Y') while still using errors='coerce'. """

df['Date_Str'] = pd.to_datetime(df['Date_Str'], format='mixed', errors='coerce')
df

        Event   Date_Str
0  Conference 2024-03-15
1    Workshop 2024-04-20
2     Seminar        NaT
3      Meetup 2024-05-15

In [72]:
#Task 3: Create a new column Year that extracts the year from the converted datetime column.

df['Year'] = df['Date_Str'].apply(lambda x: x.year if pd.notnull(x) else None)

df

        Event   Date_Str    Year
0  Conference 2024-03-15  2024.0
1    Workshop 2024-04-20  2024.0
2     Seminar        NaT     NaN
3      Meetup 2024-05-15  2024.0

In [73]:
#Task 4 (Bonus): Convert a single string '2024-12-25 14:30:00' to a Timestamp. Then extract the hour and minute from it.

single_datetime = pd.to_datetime('2024-12-25 14:30:00')
print(single_datetime.hour)
print(single_datetime.minute)

14
30

In [74]:
#Day 6, Topic 2: The .dt Accessor
import pandas as pd

In [75]:
dates = pd.Series(pd.to_datetime(['2026-01-05', '2026-01-06', '2026-01-07']))

print(dates.dt.year)
print(dates.dt.month)
print(dates.dt.day)
print(dates.dt.hour)
print(dates.dt.minute)
print(dates.dt.second)

0    2026
1    2026
2    2026
dtype: int32
0    1
1    1
2    1
dtype: int32
0    5
1    6
2    7
dtype: int32
0    0
1    0
2    0
dtype: int32
0    0
1    0
2    0
dtype: int32
0    0
1    0
2    0
dtype: int32

In [76]:
#Day of Week, Quarter, and More
print(dates.dt.dayofweek)
print(dates.dt.day_name())
print(dates.dt.quarter)
print(dates.dt.is_month_start)
print(dates.dt.is_month_end)
print(dates.dt.is_leap_year)
print(dates.dt.isocalendar())

0    0
1    1
2    2
dtype: int32
0       Monday
1      Tuesday
2    Wednesday
dtype: object
0    1
1    1
2    1
dtype: int32
0    False
1    False
2    False
dtype: bool
0    False
1    False
2    False
dtype: bool
0    False
1    False
2    False
dtype: bool
   year  week  day
0  2026     2    1
1  2026     2    2
2  2026     2    3

In [77]:
#Titanic Example (Simulated Dates)
df = pd.read_csv('titanic.csv')
# Simulate: assume tickets were booked 30 days before departure (April 15, 1912)
departure = pd.to_datetime('1912-04-15')
df['Booking_Date'] = departure - pd.Timedelta(days=30)
# Add some variation: random offset
import numpy as np
np.random.seed(42)
df['Booking_Date'] = df['Booking_Date'] + pd.to_timedelta(np.random.randint(-5, 5, size=len(df)), unit='D')

# Now use .dt accessor
df['Booking_Month'] = df['Booking_Date'].dt.month
df['Booking_Weekday'] = df['Booking_Date'].dt.day_name()
print(df[['Booking_Date', 'Booking_Month', 'Booking_Weekday']].head())

  Booking_Date  Booking_Month Booking_Weekday
0   1912-03-17              3          Sunday
1   1912-03-14              3        Thursday
2   1912-03-18              3          Monday
3   1912-03-15              3          Friday
4   1912-03-17              3          Sunday

In [78]:
#String Formatting with .strftime()
df['Booking_Str'] = df['Booking_Date'].dt.strftime('%d %B %Y')
df['Booking_Str'].head()

0    17 March 1912
1    14 March 1912
2    18 March 1912
3    15 March 1912
4    17 March 1912
Name: Booking_Str, dtype: object

In [79]:
#Boolean Filtering with .dt
mondays_bookings = df[df['Booking_Date'].dt.dayofweek == 0]

len(mondays_bookings)

190

In [80]:
#Practice Activity: .dt Accessor
import pandas as pd
import numpy as np

df = pd.read_csv('titanic.csv')

departure = pd.to_datetime('1912-04-15')
df['Booking_Date'] = departure - pd.Timedelta(days=30)
np.random.seed(42)
df['Booking_Date'] = df['Booking_Date'] + pd.to_timedelta(np.random.randint(-5, 5, size=len(df)), unit='D')

In [81]:
#Task 1: Create a new column Booking_Quarter containing the quarter (1–4) of the Booking_Date. Use .dt.quarter.

df['Booking_Quarter'] = df['Booking_Date'].dt.quarter
df[['Booking_Date', 'Booking_Quarter']].head(10)

  Booking_Date  Booking_Quarter
0   1912-03-17                1
1   1912-03-14                1
2   1912-03-18                1
3   1912-03-15                1
4   1912-03-17                1
5   1912-03-20                1
6   1912-03-13                1
7   1912-03-17                1
8   1912-03-18                1
9   1912-03-15                1

In [83]:
"""Task 2: Create a new column Booking_Weekend that is True if the booking day is Saturday or Sunday, 
False otherwise. Use .dt.dayofweek (Monday=0, Sunday=6)."""

df['Booking_Weekend'] = df['Booking_Date'].dt.dayofweek >= 5
df[['Booking_Date', 'Booking_Weekend']].head()

  Booking_Date  Booking_Weekend
0   1912-03-17             True
1   1912-03-14            False
2   1912-03-18            False
3   1912-03-15            False
4   1912-03-17             True

In [84]:
#Task 3: Count how many bookings were made in each month. Use .dt.month and .value_counts().

df['Booking_Date'].dt.month.value_counts()

Booking_Date
3    891
Name: count, dtype: int64

In [85]:
#Task 4: Filter the DataFrame to show only bookings made on the first day of the month. Use .dt.is_month_start.

month_start = df[df['Booking_Date'].dt.is_month_start]
len(month_start)

0

In [86]:
"""Task 5 (Bonus): Format the Booking_Date as a string like "Monday, 16 March 1912" using 
.dt.strftime() with format '%A, %d %B %Y'. Display the first 5 rows."""

df['format_date'] = df['Booking_Date'].dt.strftime('%A %d %B %Y')

df[['Booking_Date', 'format_date']].head()

  Booking_Date             format_date
0   1912-03-17    Sunday 17 March 1912
1   1912-03-14  Thursday 14 March 1912
2   1912-03-18    Monday 18 March 1912
3   1912-03-15    Friday 15 March 1912
4   1912-03-17    Sunday 17 March 1912