In [2]:
#Day 4, Topic 3: Aggregating Multiple Columns

import pandas as pd
df = pd.read_csv('titanic.csv')

In [3]:
#Dictionary Approach – One Function per Column
result = df.groupby('Pclass').agg({
    'Age': 'mean', 
    'Fare': 'sum',
    'Survived': 'sum'
})

result

              Age        Fare  Survived
Pclass
1       38.233441  18177.4125       136
2       29.877630   3801.8417        87
3       25.140620   6714.6951       119

In [4]:
#Multiple Functions per Column – List Approach
result = df.groupby('Pclass').agg({
    'Age': ['mean', 'median', 'std'],
    'Fare': ['sum', 'max']
})

result

              Age                          Fare
             mean median        std         sum       max
Pclass
1       38.233441   37.0  14.802856  18177.4125  512.3292
2       29.877630   29.0  14.001077   3801.8417   73.5000
3       25.140620   24.0  12.495398   6714.6951   69.5500

In [5]:
#Mixed Aggregations – Single and Multiple
result = df.groupby('Embarked').agg({
    'Age': 'median',
    'Fare': ['mean', 'max'],
    'Survived': 'sum'
})

result

            Age       Fare           Survived
         median       mean       max      sum
Embarked
C          29.0  59.954144  512.3292       93
Q          27.0  13.276030   90.0000       30
S          28.0  27.079812  263.0000      217

In [6]:
#Named Aggregations (Clean Column Names)
result = df.groupby('Sex').agg(
    avg_age=('Age', 'mean'),
    total_fare=('Fare', 'sum'),
    survivors=('Survived', 'sum'),
    survival_pct=('Survived', 'mean')
)

result

          avg_age  total_fare  survivors  survival_pct
Sex
female  27.915709  13966.6628        233      0.742038
male    30.726645  14727.2865        109      0.188908

In [7]:
#Grouping by Multiple Columns with Named Aggregations
result = df.groupby(['Pclass', 'Sex']).agg(
    count=('PassengerId', 'count'),
    avg_age=('Age', 'mean'),
    avg_fare=('Fare', 'mean'),
    survived=('Survived', 'sum')
)

result

               count    avg_age    avg_fare  survived
Pclass Sex
1      female     94  34.611765  106.125798        91
       male      122  41.281386   67.226127        45
2      female     76  28.722973   21.970121        70
       male      108  30.740707   19.741782        17
3      female    144  21.750000   16.118810        72
       male      347  26.507589   12.661633        47

In [8]:
#Practice Activity: Multi‑Column Aggregations
import pandas as pd
df = pd.read_csv('titanic.csv')

In [9]:
"""Task 1: Group by Pclass and compute:
Average Age
Total Fare
Number of survivors (Survived sum)
Use a dictionary with single functions for each column."""

pclass_stats = df.groupby('Pclass').agg({
    'Age': 'mean',
    'Fare': 'sum',
    'Survived': 'sum'
})

pclass_stats

              Age        Fare  Survived
Pclass
1       38.233441  18177.4125       136
2       29.877630   3801.8417        87
3       25.140620   6714.6951       119

In [10]:
"""Task 2: Group by Embarked. For Age, compute mean and min. For Fare, compute sum and max. 
Use a dictionary with lists for multiple functions."""

embarked_stats = df.groupby('Embarked').agg({
    'Age': ['mean', 'min'],
    'Fare': ['sum', 'max'],
})

embarked_stats

                Age              Fare
               mean   min         sum       max
Embarked
C         30.814769  0.42  10072.2962  512.3292
Q         28.089286  2.00   1022.2543   90.0000
S         29.445397  0.67  17439.3988  263.0000

In [11]:
"""Task 3: Use named aggregations to group by Sex and produce a DataFrame with columns:
passenger_count (count of rows)
avg_fare
max_age
survival_rate (mean of Survived)"""

result = df.groupby('Sex').agg(
    passenger_count=('PassengerId', 'count'),
    avg_fare=('Fare', 'mean'),
    max_age=('Age', 'max'),
    survival_rate=('Survived', 'mean')
)

result

        passenger_count   avg_fare  max_age  survival_rate
Sex
female              314  44.479818     63.0       0.742038
male                577  25.523893     80.0       0.188908

In [12]:
"""Task 4: Group by both Pclass and Embarked. Use named aggregations to compute:
total_passengers (count)
avg_fare
total_survivors (sum of Survived)"""

result = df.groupby(['Pclass', 'Embarked']).agg(
    total_passengers=('PassengerId', 'count'),
    avg_fare=('Fare', 'mean'),
    total_survivors=('Survived', 'sum')
)

result

                 total_passengers    avg_fare  total_survivors
Pclass Embarked
1      C                       85  104.718529               59
       Q                        2   90.000000                1
       S                      127   70.364862               74
2      C                       17   25.358335                9
       Q                        3   12.350000                2
       S                      164   20.327439               76
3      C                       66   11.214083               25
       Q                       72   11.183393               27
       S                      353   14.644083               67

In [13]:
"""Task 5 (Bonus): Create a new column AgeGroup with bins [0, 18, 35, 60, 100] and labels 
['Child', 'Young Adult', 'Adult', 'Senior']. Then group by AgeGroup and Sex, and compute the average 
fare and survival rate using named aggregations."""

df['AgeGroup'] = pd.cut(df['Age'], bins=[0, 18, 35, 60, 100], labels=['Child', 'Young Adult', 'Adult', 'Senior'])

result = df.groupby(['AgeGroup', 'Sex']).agg(
    avg_fare=('Fare', 'mean'),
    survival_rate=('Survived', 'mean')
)

result

C:\Users\Faizan Toheed\AppData\Local\Temp\ipykernel_13324\812471641.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  result = df.groupby(['AgeGroup', 'Sex']).agg(

                     avg_fare  survival_rate
AgeGroup    Sex
Child       female  36.765626       0.676471
            male    28.416023       0.338028
Young Adult female  45.260418       0.783333
            male    22.194255       0.180672
Adult       female  61.717739       0.771429
            male    34.483134       0.192000
Senior      female  55.848600       1.000000
            male    39.085311       0.105263

In [14]:
#Day 4, Topic 4: Grouping by Multiple Columns
import pandas as pd

df = pd.read_csv('titanic.csv')

In [15]:
#Basic Multi‑Column GroupBy
grouped = df.groupby(['Pclass', 'Sex'])
avg_fare = grouped['Fare'].mean()
avg_fare

Pclass  Sex
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64

In [16]:
#Accessing Results from Multi‑Column GroupBy
avg_fare.loc[(1, 'female')]

np.float64(106.12579787234043)

In [17]:
# All stats for first class (both sexes)
avg_fare.loc[1]

Sex
female    106.125798
male       67.226127
Name: Fare, dtype: float64

In [18]:
#Flattening the Result with .reset_index()
avg_fare_flat = avg_fare.reset_index(name='avg_fare')
avg_fare_flat

   Pclass     Sex    avg_fare
0       1  female  106.125798
1       1    male   67.226127
2       2  female   21.970121
3       2    male   19.741782
4       3  female   16.118810
5       3    male   12.661633

In [19]:
#Using .agg() with Multiple Columns
result = df.groupby(['Pclass', 'Sex']).agg(
    total_passengers=('PassengerId', 'count'),
    avg_age=('Age', 'mean'),
    avg_fare=('Fare', 'mean'),
    survival_rate=('Survived', 'mean')
).reset_index()

result

   Pclass     Sex  total_passengers    avg_age    avg_fare  survival_rate
0       1  female                94  34.611765  106.125798       0.968085
1       1    male               122  41.281386   67.226127       0.368852
2       2  female                76  28.722973   21.970121       0.921053
3       2    male               108  30.740707   19.741782       0.157407
4       3  female               144  21.750000   16.118810       0.500000
5       3    male               347  26.507589   12.661633       0.135447

In [20]:
#Grouping by Three or More Columns
result = df.groupby(['Pclass', 'Sex', 'Embarked']).agg(
    count=('PassengerId', 'count'),
    avg_fare=('Fare', 'mean')
).reset_index()

result

    Pclass     Sex Embarked  count    avg_fare
0        1  female        C     43  115.640309
1        1  female        Q      1   90.000000
2        1  female        S     48   99.026910
3        1    male        C     42   93.536707
4        1    male        Q      1   90.000000
5        1    male        S     79   52.949947
6        2  female        C      7   25.268457
7        2  female        Q      2   12.350000
8        2  female        S     67   21.912687
9        2    male        C     10   25.421250
10       2    male        Q      1   12.350000
11       2    male        S     97   19.232474
12       3  female        C     23   14.694926
13       3  female        Q     33   10.307833
14       3  female        S     88   18.670077
15       3    male        C     43    9.352237
16       3    male        Q     39   11.924251
17       3    male        S    265   13.307149

In [21]:
#The as_index=False Parameter
result = df.groupby(['Pclass', 'Sex'], as_index=False)['Fare'].mean()
result

   Pclass     Sex        Fare
0       1  female  106.125798
1       1    male   67.226127
2       2  female   21.970121
3       2    male   19.741782
4       3  female   16.118810
5       3    male   12.661633

In [22]:
#Practice Activity: Multi‑Column GroupBy

import pandas as pd
df = pd.read_csv('titanic.csv')

In [23]:
#Task 1: Group by Pclass and Embarked. Compute the average fare for each subgroup. Use .reset_index() to 
# flatten the result.

result = df.groupby(['Pclass', 'Embarked'])['Fare'].mean().reset_index()
result

   Pclass Embarked        Fare
0       1        C  104.718529
1       1        Q   90.000000
2       1        S   70.364862
3       2        C   25.358335
4       2        Q   12.350000
5       2        S   20.327439
6       3        C   11.214083
7       3        Q   11.183393
8       3        S   14.644083

In [24]:
"""Task 2: Group by Sex and Pclass. Use .agg() to compute:
Number of passengers (count)
Average Age
Survival rate (mean of Survived)
Flatten the result with .reset_index()."""

result = df.groupby(['Sex', 'Pclass']).agg(
    number_of_passengers=('PassengerId', 'count'),
    avg_age=('Age', 'mean'),
    survival_rate=('Survived', 'mean')
).reset_index()

result

      Sex  Pclass  number_of_passengers    avg_age  survival_rate
0  female       1                    94  34.611765       0.968085
1  female       2                    76  28.722973       0.921053
2  female       3                   144  21.750000       0.500000
3    male       1                   122  41.281386       0.368852
4    male       2                   108  30.740707       0.157407
5    male       3                   347  26.507589       0.135447

In [25]:
"""Task 3: Use as_index=False to group by Embarked and Sex, and compute the total fare collected per subgroup. 
Which subgroup paid the most total fare?"""

result = df.groupby(['Embarked', 'Sex'], as_index=False)['Fare'].sum()
result

top_sub = result.loc[result['Fare'].idxmax()]

top_sub

Embarked            S
Sex              male
Fare        9574.9903
Name: 5, dtype: object

In [26]:
"""Task 4: Create a new column FamilySize = SibSp + Parch + 1. Then group by three columns: 
Pclass, Sex, and FamilySize. Compute the count of passengers in each subgroup. 
Sort by count descending. Which subgroup is most common?"""

df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

result = df.groupby(['Pclass', 'Sex', 'FamilySize'])['PassengerId'].count().sort_values(ascending=False)
result.index[0]

(np.int64(3), 'male', np.int64(1))

In [27]:
"""Task 5 (Bonus): Group by Pclass and Embarked. Use a dictionary inside .agg() to compute:
Age: ['mean', 'min', 'max']
Fare: 'sum'
Survived: 'mean'
Flatten the result and rename columns appropriately."""

result = df.groupby(['Pclass', 'Embarked']).agg(
    {
        'Age':['mean', 'min', 'max'],
        'Fare': 'sum',
        'Survived': 'mean'
    }
).reset_index()
result.columns = ['_'.join(col).strip() for col in result.columns.values]
result.rename(columns={
    'Age': 'Age_stats',
    'Fare': 'Total_Fare',
    'Survived': 'Survival_Rate'
})

   Pclass_ Embarked_   Age_mean  Age_min  Age_max   Fare_sum  Survived_mean
0        1         C  38.027027    16.00     71.0  8901.0750       0.694118
1        1         Q  38.500000    33.00     44.0   180.0000       0.500000
2        1         S  38.152037     0.92     80.0  8936.3375       0.582677
3        2         C  22.766667     1.00     36.0   431.0917       0.529412
4        2         Q  43.500000    30.00     57.0    37.0500       0.666667
5        2         S  30.386731     0.67     70.0  3333.7000       0.463415
6        3         C  20.741951     0.42     45.5   740.1295       0.378788
7        3         Q  25.937500     2.00     70.5   805.2043       0.375000
8        3         S  25.696552     1.00     74.0  5169.3613       0.189802