In [1]:
#Day 4, Topic 7: Grouping with .value_counts() and .nunique()

import pandas as pd
df = pd.read_csv('titanic.csv')

In [2]:
#.value_counts() on Grouped Data
sex_counts = df.groupby('Pclass')['Sex'].value_counts()
sex_counts

Pclass  Sex
1       male      122
        female     94
2       male      108
        female     76
3       male      347
        female    144
Name: count, dtype: int64

In [3]:
#Flatten for readability:
sex_counts.reset_index(name='count')

   Pclass     Sex  count
0       1    male    122
1       1  female     94
2       2    male    108
3       2  female     76
4       3    male    347
5       3  female    144

In [4]:
#Normalized .value_counts() for Proportions
sex_pct = df.groupby('Pclass')['Sex'].value_counts(normalize=True)
sex_pct

Pclass  Sex
1       male      0.564815
        female    0.435185
2       male      0.586957
        female    0.413043
3       male      0.706721
        female    0.293279
Name: proportion, dtype: float64

In [5]:
#.nunique() – Count Unique Values per Group
unique_tickets = df.groupby('Pclass')['Ticket'].nunique()
unique_tickets

Pclass
1    147
2    140
3    394
Name: Ticket, dtype: int64

In [8]:
df.groupby('Embarked').agg(
    unique_passengers=('PassengerId', 'nunique'),
    unique_names=('Name', 'nunique'),
    unique_cabins=('Cabin', 'nunique')
)

          unique_passengers  unique_names  unique_cabins
Embarked
C                       168           168             57
Q                        77            77              3
S                       644           644             89

In [11]:
#Combining .value_counts() with .unstack() for Cross‑Tabulation
sex_table = df.groupby('Pclass')['Sex'].value_counts().unstack()
sex_table

Sex     female  male
Pclass
1           94   122
2           76   108
3          144   347

In [12]:
#.value_counts() on Multiple Columns Simultaneously
combo_counts = df[['Pclass', 'Sex', 'Survived']].value_counts().reset_index(name='count')
combo_counts.head()

   Pclass     Sex  Survived  count
0       3    male         0    300
1       1  female         1     91
2       2    male         0     91
3       1    male         0     77
4       3  female         0     72

In [13]:
#Practice Activity: .value_counts() and .nunique()
import pandas as pd

df = pd.read_csv('titanic.csv')

In [14]:
"""Task 1: Use .groupby() and .value_counts() to count how many passengers survived vs. did not survive within each Pclass. 
Flatten the result with .reset_index()"""

passen = df.groupby('Pclass')['Survived'].value_counts().reset_index(name='counts')
passen

   Pclass  Survived  counts
0       1         1     136
1       1         0      80
2       2         0      97
3       2         1      87
4       3         0     372
5       3         1     119

In [15]:
"""Task 2: Repeat Task 1, but use normalize=True to get survival proportions per class. 
Which class had the highest survival rate?"""

prop = df.groupby('Pclass')['Survived'].value_counts(normalize=True).reset_index(name='Percentage')

prop

   Pclass  Survived  Percentage
0       1         1    0.629630
1       1         0    0.370370
2       2         0    0.527174
3       2         1    0.472826
4       3         0    0.757637
5       3         1    0.242363

In [16]:
"""Task 3: Use .groupby() and .nunique() to find out how many unique ticket numbers exist for each 
combination of Embarked and Pclass. Flatten the result."""

result = df.groupby(['Embarked', 'Pclass'])['Ticket'].nunique().reset_index()
result

  Embarked  Pclass  Ticket
0        C       1      57
1        C       2      12
2        C       3      53
3        Q       1       1
4        Q       2       3
5        Q       3      62
6        S       1      90
7        S       2     125
8        S       3     279

In [17]:
#Task 4: For each Embarked port, count how many unique passenger names exist. 
# (Hint: group by Embarked, then use .nunique() on Name.)

result = df.groupby('Embarked')['Name'].nunique()

result

Embarked
C    168
Q     77
S    644
Name: Name, dtype: int64

In [18]:
"""Task 5 (Bonus): Create a contingency table showing the count of passengers by Pclass (rows) and Embarked (columns) 
using .groupby() and .value_counts() with .unstack(). Then, add a "Total" column summing each row."""

contingency_table = df.groupby('Pclass')['Embarked'].value_counts().unstack()
contingency_table['Total'] = contingency_table.sum(axis=1)
contingency_table

Embarked   C   Q    S  Total
Pclass
1         85   2  127    214
2         17   3  164    184
3         66  72  353    491